confidential-containers/guest-components

.github/workflows/ci.yml

The signature verification module relies on `sequoia-openpgp`, and `sequoia-openpgp` relies on nettle-sys. To build nettle-sys successfully, `clang` `llvm` `pkg-config` `nettle-dev` must be installed in the test environment.

CI: Install nettle-sys building dependencies

---

scripts/build_attestation_agent.sh
tests/integration.rs

Current unit tests in pull module only covered the tests for container
image encrypted by a public key file.
The integration test verify the container images encrypted by an KBS.
How to create KBS encrypted container image is documented in:
test_data/generate_test_data.md
It will first launch an attestation-agent daemon build
with sample KBS support. Then it will try to pull an KBS encrypted
container image to verify pull_image API.

tests: Add integration test for KBS encrypted OCI image 

---

signature/Cargo.toml
signature/src/policy/mod.rs
signature/src/policy/policy_requirement.rs

Due to some special dependencies and implementations of the signature module,
musl compilation fails when integrating with Kata-agent. This commit solves these problems.
cc @arronwy

[Signature] Solve the compiling problem integrated with kata-agent

---

src/bundle.rs

Refine create_runtime_config() by:
1) add more comments
2) fix error in generating annotations
3) add support for missed annotations

Refine create_runtime_config()

---

README.md
docs/ccv1_image_security_design.md

There are multiple image signing and verification protocols/solutions available now, and there’s no standardization work for image signing yet. So in the design of confidential containers, we should support different signature mechanisms with modular implementation.

Modify security design document

---

Cargo.toml
src/decoder/mod.rs
src/decrypt.rs
src/validate.rs

Instead of using ocicrypt-rs from `main`, let's pin a specific version,
which is known to be working, and move to newer commits as it becomes
required / desired, instead of keep following ocicrypt-rs' main.
Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

Pin a specific version of ocicrypt-rs

---

.github/workflows/ci.yml
Cargo.toml

The CI workflow is failing at the moment as the currently pinned
version of ocicrypt-rs has conflicting versions of tonic and prost in
it's dependencies. Let try the latest version to see if that helps
Fixes: #41
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

ci: Update the pinned version of ocicrypt-rs

---

.github/workflows/ci.yml
Cargo.toml
signature/src/image/digest.rs
signature/src/image/mod.rs
signature/src/mechanism/simple/mod.rs
signature/src/mechanism/simple/verify.rs
signature/src/policy/mod.rs
signature/src/policy/policy_requirement.rs
signature/src/policy/ref_match.rs

The unit tests for signature submodule is not enabled by the CI.
Fixes: #48

Enable CI check for signature module

---

signature/src/agent.rs
test_data/ocicrypt_keyprovider.conf
tests/common/mod.rs

due to
https://github.com/confidential-containers/attestation-agent/issues/76,
all CCv0 components should use an uniform port
setting, which is beneficial to dev/test/deploy.
The port setting is the same as CCv0 in
https://github.com/confidential-containers/kata-containers-CCv0/blob/CCv0/src/agent/src/image_rpc.rs#L31
Signed-off-by: Xynnn007 <mading.ma@alibaba-inc.com>

fix: uniform port setting for AA

---

.github/workflows/ci.yml
Cargo.toml
src/image.rs
src/snapshots/mod.rs
src/snapshots/occlum/mod.rs
src/snapshots/occlum/unionfs.rs

1 Add occlum/unionfs.rs only for Occlum adaption.
2 Add overlay_feature and occlum_feature for differentiate usage.
3 Mount the host path to the specified path on Occlum.
4 Move the pulled image to the specified path on Occlum.
5 Create the required environment for Occlum.
Signed-off-by: Zhiwei Han <zhiwei1.han@intel.com>

snapshot: Add occlum/unionfs.rs to adapt to pulling images in the LibOS Occlum environment

---

signature/src/mechanism/mod.rs

Fix the building error of kata-agent:
error: future cannot be sent between threads safely
--> src/image_rpc.rs:265:50
|
265 |       ) -> ttrpc::Result<image::PullImageResponse> {
|  __________________________________________________^
266 | |         match self.pull_image(&req).await {
267 | |             Ok(r) => {
268 | |                 let mut resp = image::PullImageResponse::new();
...   |
275 | |         }
276 | |     }
| |_____^ future created by async block is not `Send`
|
= help: the trait `Sync` is not implemented for `dyn signature::mechanism::SignScheme`
note: future is not `Send` as this value is used across an await

signature: Add Send/Sync support for SignScheme trait

---

src/pull.rs

The `pub struct PullClient` has a method `pub async fn pull_layers` to download, decrypt and decompress layers. In the [line 137](https://github.com/confidential-containers/image-rs/blob/d772f4d23d814c1f48066ea917ce1e426996be64/src/pull.rs#L137), the client will assign the value `layer.digest.clone()`  which is the layer digest from the image manifest, to the `layer_meta.uncompressed_digest` and `layer_meta.compressed_digest` if the layer is uncompressed. 
However, if a layer is encrypted and uncompressed, the digest from the image manifest is evaluated on the **encrypted layer**, obviously which is not equal to the digest evaluated on the **plaintext layer**.
The client need to re-evaluate the digest on the plaintext layer for the uncompressed layer, just like for the compressed layer. …

fix: correct digest for uncompressed layer

---

Cargo.toml
libs/test-utils/Cargo.toml
libs/test-utils/src/lib.rs
src/decoder/mod.rs
src/image.rs
src/meta_store.rs
src/pull.rs

Split the `pull_layers()` method which now calls `handle_layer()` to
reduce the length and complexity of the original function.
Also implemented `TryFrom` for `Compression` (and added some unit tests)
to further simplify the code.
> **Note:**
>
> This PR also contains a new `assert_result!()` test macro that was
> originally written by me as `assert_log_level!()` for Kata Containers
> on:
>
> - https://github.com/kata-containers/kata-containers/pull/65
>
> ... but which now exists in Kata Containers as `assert_result!()` here:
>
> - https://github.com/kata-containers/kata-containers/blob/2b5dc2ad39b9b077246e5bc17c91cc2578c22497/src/libs/test-utils/src/lib.rs#L68
Fixes: #54.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

pull: Refactor pull_layers()

---

src/pull.rs

Fix the lint error:
```plaintext
error: the borrowed expression implements the required traits
Error:    --> src/pull.rs:150:42
|
150 |                     sha2::Sha256::digest(&plaintext_layer.as_slice())
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `plaintext_layer.as_slice()`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
error: the borrowed expression implements the required traits
Error:    --> src/pull.rs:156:42
|
156 |                     sha2::Sha512::digest(&plaintext_layer.as_slice())
|                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `plaintext_layer.as_slice()` …
```

fix: CI lint

---

.github/workflows/ci.yml
.github/workflows/ci_eaa_kbc.yml
Cargo.toml
signature/Cargo.toml
signature/src/agent.rs
src/config.rs

Enclave-cc plans to replace the gRPC AA (attestation agent) with an native AA in the [issue 21](https://github.com/confidential-containers/enclave-cc/issues/21) . Currently, the signature sub-crate in this repo only supports communicating AA via gRPC socket. This PR adds an native signature client that uses an native AA to communicate with the remote KBS.
The PR uses the environment variable "ENABLE_SECURITY_VALIDATE" to enable image signature verification and loads the config file of the ocicrypt-rs to determine whether the AA is native.
Signed-off-by: haokun.xing <haokun.xin@intel.com>

features: support native signature client

---

src/signature/payload/simple_signing.rs

This commit defined a Simple Signing payload of image-rs' own, which avoids "leaking" sigstore-rs types when using SigPayload structure in image-rs.
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>

fix: remove hard reference of SimpleSigning in sigstore-rs

---

Cargo.toml

Fixed ci error in nightly.
Close https://github.com/confidential-containers/image-rs/issues/78

fix: ci error about rstest

---

src/image.rs
src/pull.rs

Some layers may failed to pull with network issues, orchectration framwork like k8s will trigger repull, we can skip layers pulled successfully last time.

image: Update layer db with all success pulled layers

---

Cargo.toml

Add a feature that can be specificed by crates that include the image-rs crate to build image-rs with all default features except cosign.
Fixes confidential-containers#88
Signed-off-by: Matthew Arnold <mattarno@uk.ibm.com>

Add feature for image-rs with defaults except cosign

---

docs/quickstart/image_signing.md

minor tweak to image signing quickstart guide. making it easier to copy the example policy file
Fixes: #111
Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

docs: remove commas in example policy.json

---

.github/workflows/ci_eaa_kbc.yml
Cargo.toml
src/auth/mod.rs
src/config.rs
src/image.rs
src/lib.rs
src/signature/mechanism/cosign/mod.rs
src/signature/mechanism/mod.rs
src/signature/mechanism/simple/mod.rs
src/signature/mod.rs
src/signature/policy/mod.rs
src/signature/policy/policy_requirement.rs
tests/credential.rs
tests/image_decryption.rs
tests/signature_verification.rs

For non-confidential container scenarios, `secure_channel` is not supported. This commit brings a feature `getresource` to control whether to enable `secure_channel`.
Also, add flexibly configurable for paths to support both confidential scenarios and non-confidential scenarios.
Close https://github.com/confidential-containers/image-rs/issues/110
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>

feat: add feature to control secure_channel

---

.github/workflows/ci.yml
Cargo.toml

Close https://github.com/confidential-containers/image-rs/issues/121

fix: use ttrpc instead of grpc as default protocol

---

Cargo.toml

enclave-cc should enable `signature-cosign` by default : https://github.com/confidential-containers/enclave-cc/blob/main/src/enclave-agent/Cargo.toml#L16
Kata-cc should enable `signature-simple` by default: https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/Cargo.toml#L77

Fix features of kata-cc and enclave-cc

---

Cargo.toml

Latest oci-distribution have fixed faile to pull `ubuntu` image from docker.io: https://github.com/krustlet/oci-distribution/pull/67
Restrict sigstore-rs to use the same `oci-distribuiton` with `image-rs` to fix the build issue.

cargo: Update oci-distribution to support manifest lists

---

Cargo.toml

Let's use the latest released tag for both ocicrypt-rs and attestation-agent.

deps: Update ocicrypt-rs / attestation-agent to v0.5.0

---

.github/workflows/ci.yml
.github/workflows/ci_eaa_kbc.yml
Cargo.toml
src/signature/mechanism/cosign/mod.rs
src/signature/payload/simple_signing.rs

Fix remove ring

---

src/signature/policy/policy_requirement.rs

Now cosign is supported by s390x with `kata-cc-native-tls` feature.

Signature: delete useless notes

---

.github/workflows/ci.yml
.github/workflows/ci_eaa_kbc.yml
Cargo.toml
src/pull.rs

This new feature is used inside encalve-cc to integrate cc-kbc and generic-kbs
add "ocicrypt-rs/block-cipher" for feature `encryption`
delete "keywrap-jwe" for ocicrypt-rs
Close #143

Cargo.toml: add occlum cckbc feature

---

src/config.rs
src/image.rs
src/pull.rs

`std::thread::available_parallelism()` will get all available cpu num in host side for enclave-cc, export the config for enclave/kata agent to decide.
Thanks @mythi for point this out.
DEFAULT_MAX_CONCURRENT_DOWNLOAD is set to 3 which is the same default config for dockerd.

config: Add max_concurrent_download for pull operation

---

Cargo.toml

- Update ocicrypt-rs & attestation-agent to use the v0.6.0 release tag

dep: Update ocicrypt-rs & attestation-agent

---

tests/common/mod.rs
tests/credential.rs
tests/image_decryption.rs
tests/signature_verification.rs

- If the AA process for integration tests fails to come up properly the tests do not abort.
- On failed tests the AA process is not killed, because the teardown fn is not called.
- Garbage collection of tempfile::tempdir doesn't work for overlayfs mounted bundles
The changes probe for an unexpected exit, instruct tokio to kill the process on `drop()` of the `Command`, and umount the rootfs on a successful pull
```bash
running 1 test
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: transport error
Caused by:
0: error creating server listener: Address already in use (os error 98)
1: Address already in use (os error 98)', app/src/main.rs:31:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test test_decrypt_layers::case_1 ... FAILED …
```

Add some robustness fixes to integration tests

---

.github/workflows/aa_occlum_sgx.yml
attestation-agent/ci/occlum.yaml

Built binary `occlum-attester` will be put in the top `target` directory of the workspace.

ci: Occlum: fix ci test

---

attestation-agent/README.md

Port of https://github.com/confidential-containers/attestation-agent/pull/218, which didn't make it in the repo merge.

Add missing attesters to Readme

---

attestation-agent/kbs_protocol/src/lib.rs
attestation-agent/kbs_protocol/src/types.rs

Currently the String returned from attestation() is quoted, because Value["token"] is a Value, and to_string() returns the "string representation" of the Value instead of the contained string. Introduce a struct representing the data returned from /attest, and deserialize into that so that we return the correct, raw string.
Closes: https://github.com/confidential-containers/attestation-agent/pull/214

kbs_protocol: Return unquoted string from attestation()

---

attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/snp/mod.rs

virtee/sev 1.2 broke the API from 1.1, but we ended up using it in az-snp-vtpm. Now we see issue building kbs when multiple conflicting versions of virtee/sev are required. Bump the dependency here and adapt the code to the new API.

aa/attester: Update virtee/sev dep to 1.2

---

.github/workflows/image_rs_build.yml
image-rs/scripts/build_attestation_agent.sh

After merging attestation-agent into image-rs, we do not need to pull attestation-agent separately when doing the integration test. It is only needed to build the attestation-agent inside the current workspace.
cc @taoohong

ci: Fix integration test for image-rs

---

image-rs/Cargo.toml
image-rs/src/digest.rs
image-rs/src/lib.rs
image-rs/src/pull.rs
image-rs/src/stream.rs

Optimize implementation of image-rs/stream:
1) unify digest algorithm prefixes
2) avoid unnecessary memory copy
3) simplify function stream_processing()
4) get rid of flume crate to reduce dependency

Optimize implementation of image-rs/stream

---

image-rs/docs/pull_image_with_nydus.md
image-rs/src/image.rs
image-rs/src/nydus/service.rs

1. Fixed the bug 'read only filesystem' when start container with Nydus image rootfs.
2. Add doc about how to pull encrypted Nydus image with image-rs to accelerate container startup process.

Add doc about how to pull encrypted Nydus image with image-rs

---

Cargo.toml
attestation-agent/deps/crypto/src/teekey.rs

Port of https://github.com/confidential-containers/attestation-agent/pull/211
---
Fixes https://github.com/confidential-containers/guest-components/issues/184

AA: use URL safe base64 encoding for TeePubKey

---

attestation-agent/kbc/src/cc_kbc/mod.rs
attestation-agent/kbs_protocol/src/lib.rs

Currently, our default host URL format for KBS is http://IP:PORT, But in productization, we may give host URL more forms. For example: http://my-kbs.com , http://my-kbs.com/user-alice Therefore, it is necessary to expand the supported KBS host URL format, More precisely, it should no longer be referred to as the "host URL", but rather as the "root URL".

Adjusted the handling of URLs to support more types of hosts

---

image-rs/src/lib.rs
image-rs/src/pull.rs
image-rs/src/stream.rs

Optimize implementation of image-rs/pull by:
1) simplify implementation of async_pull_layers()
2) remove pull_layers()
3) simplify definition of pull_bootstrap()

Optimize implementation of image-rs/pull

---

.github/workflows/image_rs_build.yml
attestation-agent/Makefile
image-rs/scripts/build_attestation_agent.sh
image-rs/tests/common/mod.rs

Improving output when building and starting AA.
Placing gRPC and ttRPC binaries in different directories, so both can be cached and it is clear what feature the binary supports.
Test itself was already fixed in #271.

image-rs: improve AA build and output

---

image-rs/tests/common/mod.rs
image-rs/tests/credential.rs
image-rs/tests/image_decryption.rs
image-rs/tests/signature_verification.rs

When looking at the "Files changed" in recent PRs, there are many extraneous warnings in image-rs/tests (e.g. "unused import"). The two main causes seem to be:
(1) the appropriate annotation for an integration test is not always applied to the respective import statement, variable, etc.
(2) not all integration tests use all of the common support from image-rs/tests/common/mod.rs
This PR tries to resolve the warnings. Annotations are added to solve (1). For (2), I've added `pub mod common` to the integration tests, which could lead to actual dead code that won't get caught by warnings. This seems to be a reasonable workaround, however, due to [this issue](https://github.com/rust-lang/rust/issues/46379).

Tidy up the warnings from integration tests

---

image-rs/test_data/generate_test_data.md

With the help of @katexochen , there is a document bug found in https://github.com/confidential-containers/guest-components/actions/runs/5538239881/jobs/10107974050

docs: update generate_test_data guide link

---

image-rs/src/image.rs
image-rs/src/pull.rs
image-rs/src/resource/kbs/mod.rs
image-rs/src/signature/mechanism/simple/verify.rs
image-rs/src/signature/payload/simple_signing.rs
image-rs/src/snapshots/occlum/unionfs.rs
image-rs/src/unpack.rs
image-rs/tests/common/mod.rs
image-rs/tests/credential.rs
image-rs/tests/image_decryption.rs
image-rs/tests/signature_verification.rs

Verified with:
```
cargo clippy --all-targets --features=default  -- -D warnings
cargo clippy --all-targets --features=kata-cc-rustls-tls --no-default-features -- -D warnings
cargo clippy --all-targets --features=enclave-cc-eaakbc-rustls-tls --no-default-features -- -D warnings
cargo clippy --all-targets --features=kata-cc-native-tls --no-default-features -- -D warnings
cargo clippy --all-targets --features=enclave-cc-eaakbc-native-tls --no-default-features -- -D warnings
cargo clippy --all-targets --features=enclave-cc-cckbc-native-tls --no-default-features -- -D warnings
```
Will add to the CI once https://github.com/confidential-containers/guest-components/pull/275 is merged

image-rs: Fix the rust lint warning

---

.github/workflows/aa_cc_kbc.yml
attestation-agent/kbc/src/cc_kbc/mod.rs
attestation-agent/kbs_protocol/src/lib.rs

In enclave-cc's CI https://github.com/confidential-containers/enclave-cc/pull/188 we met the following error 
```
E0717 18:20:17.225384 2897992 remote_image.go:238] "PullImage from image service failed" err=<
rpc error: code = Internal desc = Security validate failed: error decoding response body: EOF while parsing a value at line 1 column 0
Caused by:
EOF while parsing a value at line 1 column 0
> image="ghcr.io/confidential-containers/test-container-enclave-cc:encrypted"
time="2023-07-[17](https://github.com/confidential-containers/enclave-cc/actions/runs/5573528817/jobs/10182945922?pr=188#step:16:18)T[18](https://github.com/confidential-containers/enclave-cc/actions/runs/5573528817/jobs/10182945922?pr=188#step:16:19):[20](https://github.com/confidential-containers/enclave-cc/actions/run …
```

Fix kbs url in cc-kbc

---

.github/workflows/aa_basic.yml
.github/workflows/aa_cc_kbc.yml
.github/workflows/aa_crypto.yml
.github/workflows/aa_eaa_kbc.yml
.github/workflows/aa_occlum_sgx.yml
.github/workflows/aa_release.yml
.github/workflows/aa_sample_keyprovider.yml
.github/workflows/aa_sev_kbc.yml
.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml
.gitignore

Some refactoring of workflows:
- Remove invalid filter on create trigger. This trigger doesn't allow filters.
- Only use push trigger on main (wasn't used before anyway, as there was an if statement on most jobs).
- Adding path filters to image-rs and ocicrypt-rs workflows.
- Removing if statements on jobs. The workflow triggers control when a job run, no need to filter with an if statement on a single job.
- Trying to unify naming a bit, fixing white space issues.
- Adding `workflow_dispatch` trigger to every test workflow, so they can be triggered manually where needed (like on forks).

ci: refactor workflows

---

attestation-agent/attester/src/az_snp_vtpm/mod.rs
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/sample/mod.rs
attestation-agent/attester/src/sgx_dcap/mod.rs
attestation-agent/attester/src/snp/mod.rs
attestation-agent/attester/src/tdx/mod.rs
attestation-agent/deps/crypto/src/teekey.rs

Change the API of `get_evidence` function to just performing getting evidence via calling the underlying hardware drivers.
Fixes: #283
Please do not merge this until the v0.8.0 cycle.
cc @jialez0 @fitzthum @mkulke please take a look if these changes are good for the architecture/concrete attester implementation.

attestation-agent/Attesters: refactor the trait of Attester

---

.github/workflows/image_rs_build.yml
image-rs/Cargo.toml
image-rs/src/image.rs
image-rs/src/lib.rs
image-rs/src/verity.rs

Implement image block device integrity check using dm-verity and mount the verity device in image-rs.
Notes: the kernel should be upgrade to >=6.4 for mounting the verity device with erofs tarfs.

image-rs: add image block device dm-verity and mount

---

attestation-agent/kbs_protocol/src/lib.rs
attestation-agent/kbs_protocol/src/types.rs

Currently `KbsProtocolWrapper` bootstraps itself. It detects a TEE and attempts to create an Attester object. There are situations in which it is desirable to inject an Attester implementation from the caller side (e.g. we want to wrap `get_evidence()` for a given TEE in an IPC call). 
(discussion [here](https://github.com/confidential-containers/confidential-containers/issues/136), for more context)
This is made possible by providing a builder for the wrapper. Existing code should work without modifications. The builder requires a tee and accepts an attester object optionally.
```rust
let wrapper = KbsProtocolWrapperBuilder::new().with_tee(Tee::Snp).build();
let wrapper = KbsProtocolWrapperBuilder::new()
.with_tee(Tee::Tdx)
.with_attester(brought_my_own)
.build();
```
There are some …

Provide builder for KBS Protocol Wrapper

---

attestation-agent/attester/src/lib.rs
attestation-agent/deps/crypto/src/teekey.rs
attestation-agent/kbc/src/cc_kbc/mod.rs
attestation-agent/kbs_protocol/src/lib.rs

1. Update TEE key when generate evidence
We should not use the same pair of RSA keys for a long time, as this will bring forward security issues.
This change alleviates this issue by updating the TEE key every time the attestation is redone.
2. Allow setting custom KBS certificates to enable TLS
Add parameters for setting customized KBS Root certificate when creating HTTP client, so that TLS communication can be enabled in various deployment scenarios.

Added two security enhancements to AA

---

attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/az_snp_vtpm/mod.rs
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/sample/mod.rs
attestation-agent/attester/src/sgx_dcap/mod.rs
attestation-agent/attester/src/snp/mod.rs
attestation-agent/attester/src/tdx/mod.rs
attestation-agent/kbs_protocol/src/lib.rs

Made Attester trait's get_evidence() async

---

image-rs/src/pull.rs

We use CoCo's ghcr.io repo instead of personal repo for the test images.

image pull tests: replace image ref

---

image-rs/src/pull.rs

The CI fails intermittently at asserts in the unit tests, and the error message is lost.
This PR adds a log for one of the test cases that has this problem, namely pull.rs' `test_async_pull_client`
Partly addresses [Issue 156](https://github.com/confidential-containers/guest-components/issues/156)
Perusing CI failures, this test may be one of the more common failures, e.g. assuming logs are still available, [this pr288 failure](https://github.com/confidential-containers/guest-components/actions/runs/5607682567/job/15191900400?pr=288) or [this pr278 failure](https://github.com/confidential-containers/guest-components/actions/runs/5610473139/job/15200046088?pr=278).

Add panic with error msg when test-async-pull-client fails

---

image-rs/libs/test-utils/src/lib.rs
image-rs/src/image.rs
image-rs/src/pull.rs
image-rs/src/signature/mechanism/cosign/mod.rs
image-rs/src/signature/mechanism/simple/mod.rs

The pull operation will interactive with remote registry which may have network or rate limits issue, add the retry operation for related to avoid trigger the rebuild for CI with these issues.

image-rs: Fix the flaky CI with assert_retry

---

image-rs/src/resource/kbs/mod.rs

Eventually `localhost` will fail in this constructor, because it's not a valid URL.
https://github.com/confidential-containers/guest-components/blob/3eb25b1df25418f99140d11f9855e9ab5d0b0a13/attestation-agent/kbc/src/cc_kbc/mod.rs#L55-L57

image-rs: change fallback kbs_uri from localhost to http://localhost

---

attestation-agent/kbs_protocol/src/lib.rs

reqwest uses the platform's native TLS stack by default, also when rusttls is enabled.
Force reqwest Client to use rustls TLS stack when rust-crypto feature is enabled. This is what users most likely expect to get.

kbs_protocol: use rusttls when rust-crypto feature is enabled

---

attestation-agent/kbs_protocol/Cargo.toml
image-rs/Cargo.toml

This newly refactored `kbs_protocol` crate by default activate all attesters when background-check is enabled. This PR fixes this.
related to https://github.com/confidential-containers/enclave-cc/pull/180

Kbs protocol fix cargo toml

---

attestation-agent/kbc/Cargo.toml
attestation-agent/lib/Cargo.toml

kbs_protocol is not required by eaa_kbc
Fix the CI lint error:
Error:   --> attestation-agent/kbs_protocol/src/client/mod.rs:37:16
|
32 | pub struct KbsClient<T> {
|            --------- fields in this struct
...
37 |     pub(crate) tee_key: TeeKeyPair,
|                ^^^^^^^
38 |
39 |     pub(crate) provider: T,
|                ^^^^^^^^
...
42 |     pub(crate) http_client: reqwest::Client,
|                ^^^^^^^^^^^
...
45 |     pub(crate) kbs_host_url: String,
|                ^^^^^^^^^^^^
...
48 |     pub(crate) token: Option<Token>,
|                ^^^^^
|
= note: `-D dead-code` implied by `-D warnings`

cargo: Fix the build dependency for eaa_kbc

---

image-rs/Cargo.toml

loopdev 0.4.0 uses older bingen version which fails to build on CentOS.
This will partially fix: https://github.com/confidential-containers/cloud-api-adaptor/issues/1358. I say partially because kata-containers repo has to be updated and then CAA will be able to get these latest bits.

image-rs: Update loopdev to latest master

---

attestation-agent/attester/Cargo.toml

Having the sev dependency come from GitHub instead of crates.io was causing errors when vendoring. This change fixes it, as it makes Cargo look for sev on crates.io.
Fixes [issue 333](https://github.com/confidential-containers/guest-components/issues/333).

Remove git reference for sev

---

Cargo.toml

- Downgrade clap to get to a version that builds on rust 1.69
- clap 4.3 states that it requires rust 1.65, but it pulls in clap_lex 0.5 as a dependency, which requires rust 1.70. The newest version of clap_lex that will build on 1.69 is 0.4 and the newest version of clap that depends on 0.4 is currently 4.2.7, which is how I got to this version
Fixes: #336

versions: Downgrade clap

---

.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml

Current Kata main/CCv0 use rust toolchain version 1.69:
rust:
description: "Rust language"
notes: "'version' is the default minimum version used by this project."
version: "1.69.0"
meta:
description: |
'newest-version' is the latest version known to work when
building Kata
newest-version: "1.69.0"
Fixes: #330

ci: Use toolchain match the kata to replace the beta

---

attestation-agent/attester/Cargo.toml

Update csv-rs to support both 1.1.1 and	3.0.x versions of openssl.

aa/attester: Update csv-rs dep to rev bcf3bcc.

---

image-rs/src/verity/dmverity.rs
image-rs/src/verity/mod.rs

Redefine functions to support kata:
1) change input parameters of function `destroy_verity_device` and `destroy_dmverity_device` from `String` type  to `&str`.
2) add a function `create_dmverity_device` to call `create_verity_device`.

Verity: Redefine functions to support kata

---

attestation-agent/attester/Cargo.toml

The new version of csv-rs will support openssl 3.1.x.
Fix #346

aa/attester: Update csv-rs dep to rev 05fbacd.

---

.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml

Now we've gone to v1.72 in kata-containers, we can bump the versions we test against to stay in sync. At the moment there is a bit of duplication as 1.72 is the stable version, but that will change soon

workflows: Bump to rust 1.72

---

attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/cca/mod.rs
attestation-agent/attester/src/lib.rs
attestation-agent/kbc/Cargo.toml
attestation-agent/kbs_protocol/Cargo.toml

Support to get the CCA token in the FVP(Fixed Virtual Platform) environment, it is currently implemented by an `ioctl` which read a device exported in the userspace.
Credit to Mathias Brossard, this PR is based on his POC.

New tee type: CCA (Confidential Compute Architecture)

---

.github/workflows/aa_cc_kbc.yml
attestation-agent/lib/src/token.rs

Sorry, this is my-bad. I blindly copy-pasted the fixes from cdh into AA without paying enough attention and then just testing building it with the offline_fs_kbc and assumed that the workflows would run it for the others. It turns out that it doesn't, so I've tried to correct that and fix the code so that:
```
~/cc-guest-components/attestation-agent# make KBC=cc_kbc
DEBIANOS is: true
cd app &&  cargo build --release --no-default-features --features "cc_kbc grpc,rust-crypto" --target x86_64-unknown-linux-gnu
warning: skipping duplicate package `init` found at `/root/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/b5a32a8/demos/runtime_boot/init`
warning: skipping duplicate package `init` found at `/root/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/b5a32a8/tools/init`
warning: skipping …
```

Fix cc kbc aa param config file parsing

---

api-server-rest/src/main.rs

There is a typo in the param eval code

api-server-rest: fix aa_addr cli param

---

confidential-data-hub/kms/src/plugins/kbs/offline_fs.rs

Before this commit, if the given offline-fs-kbc file is not abled to be read when offline-fs-kbc is being initialized, an error will be raised. This will cause the whole CDH process to exit.
In real scenarios, this would require a user to embed an empty aa-offline_fs_kbc-resources.json and aa-offline_fs_kbc-keys.json to the guest image, which is meaningless.
This patch fixes this.
@stevenhorsman

cdh/kms/kbs: raise warning when failed to read file for offline-fs-kbc

---

attestation-agent/kbs_protocol/Cargo.toml
attestation-agent/kbs_protocol/src/client/rcar_client.rs
confidential-data-hub/Makefile
confidential-data-hub/docs/kms-providers/alibaba.md
confidential-data-hub/kms/src/plugins/mod.rs

When doing tests with aliyun kms and current guest components, we found some bugs and this fix will help.
cc @arronwy @mozillazg

Fix CDH & kbs_protocol

---

api-server-rest/src/aa.rs
api-server-rest/src/cdh.rs

api-server-rest: Add actionable error message for ttrcp client

---

attestation-agent/README.md
attestation-agent/docs/KBS_URI.md
attestation-agent/kbs_protocol/src/lib.rs

Fix link error

---

Cargo.lock

- csv version was updated in Cargo.toml but not in Cargo.lock.
- image crate is related to cdh's feature image decryption

Cargo.lock: update dep

---

Cargo.lock
attestation-agent/attester/src/csv/mod.rs

Add a serial number to the evidence content to identify the HYGON chip ID. This field improves the completeness of CSV evidence, allowing for different release logic to be set for different HYGON chips when setting AS policies. This modification comes from the needs of scene users.
cc @BaoshunFang @Xynnn007

Attester: Update CSV evidence format

---

Cargo.lock
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/az_snp_vtpm/mod.rs

Updated az_snp_vtpm to v0.4 revision, improved detection heuristic, so it won't conflict with other vTPM attesters.

attestion-agent: bump az_snp_vtpm attester version

---

attestation-agent/lib/src/token.rs
confidential-data-hub/kms/src/plugins/kbs/mod.rs

This is moved to /run.
Part of https://github.com/confidential-containers/cloud-api-adaptor/pull/1606

update peerpod daemon.json path

---

image-rs/src/pull.rs

Fixes #403
When using concurrent pull the resulting order of layers can vary from what's specified in the `rootfs.diff_id` of the oci image config. Layers might be mounted in the wrong order and containers are not able to run properly (e.g. `library/nginx`).
The change maintains the order of the provided `layer_descs` in the resulting `Vec<LayerMeta>` and thus the layers are mounted in the proper order.
It has been manually tested w/ 50+ coco containers. The provided test here is disabled by default, because we'll run into rate-limits w/ dockerhub and since it's a race condition it's not guaranteed to fail, either.

image-rs: fix image layer ordering

---

attestation-agent/app/build.rs
attestation-agent/app/src/rpc/attestation/mod.rs
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/tdx/mod.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent_ttrpc.rs
attestation-agent/lib/src/lib.rs
attestation-agent/protos/attestation-agent.proto

AA: Add API to extend measurement register at runtime

---

Makefile
README.md

Currently we are building AA/CDH/ASR with different and complex compiling parameters controls. To make it simpler for default cases, this commit adds a Makefile with the following assumption:
test: libc=musl, KBC=offline_fs_kbc
tdx: libc=gnu, KBC=cc_kbc_tdx
sev: libc=musl, KBC=online_sev_kbc
Fixes #373
Hi @stevenhorsman @Alex-Carter01 @fidencio @arronwy Please check if it is as expected.

Makefile: add platform Makefile to quickly build guest component binaries

---

Cargo.lock
Cargo.toml
image-rs/Cargo.toml
image-rs/src/image.rs
image-rs/src/pull.rs

The second round of updates that allow image-rs to move to released versions of the crates

chore(deps): update sigstore-rs to 0.8.0 and oci-distribution to 0.10.0

---

attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/test/kbs-config.toml
attestation-agent/kbs_protocol/test/start_kbs.sh

Before this commit, the tee-pubkey is not fully integrity-protected by binding the digest into the evidence. The update of this commit is aligned with the KBS side.
Fixes #366
cc @mythi

AA/kbs_protocol: fix RCAR handshake protocol

---

image-rs/src/snapshots/occlum/unionfs.rs
ocicrypt-rs/src/blockcipher/mod.rs
ocicrypt-rs/src/blockcipher/rand.rs

This PR is realted to Shim/rune PR https://github.com/confidential-containers/enclave-cc/pull/256 and enclave-cc PR https://github.com/confidential-containers/enclave-cc/pull/265
Creates a randomly generated key to use in unionFS that is then stored in file and passed to be mounted and read by boot enclave to use that unionFS

Random key generation

---

image-rs/src/auth/auth_config.rs

Though the PR (https://github.com/krustlet/oci-distribution/pull/48) had been merged and oci-distribution has published a new release (v0.10.0), the test could be enabled. 
Fixes #420

image-rs: enable the test of reading credentials from auth config

---

image-rs/src/config.rs
image-rs/src/image.rs
image-rs/src/lib.rs
image-rs/tests/credential.rs
image-rs/tests/image_decryption.rs
image-rs/tests/signature_verification.rs

To enable guest pulling within the kata-agent, it is imperative to configure `CC_IMAGE_WORK_DIR` variable within kata-agent before call image-rs to pull image. However, the use of `CC_IMAGE_WORK_DIR` may cause confusion in the context of kata-containers. Therefore, we can redefine constructions of `ImageConfig` and `ImageClient` that accept the image work directory as a parameter and construct instances of `ImageConfig` and `ImageClient`.
Fixes #415

image-rs: Redefine constructions of ImageClient and ImageConfig

---

attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/bin/evidence_getter.rs

This tool would help to get evidence in a tee environment, which would help to do tests.

attester: add evidence_getter binary

---

attestation-agent/coco_keyprovider/src/enc_mods/mod.rs

CI failure is caused by new cargo clippy rule in rustc 1.75.0. Refer to [this link](https://rust-lang.github.io/rust-clippy/master/index.html#map_identity).

AA: fix CI failure

---

Makefile
README.md

Adds SNP, AZ-SNP-vTPM, and AZ-TDX-vTPM to the
top-level Makefile.
@mkulke can you double-check that I did the AZ features correctly?
Also changes the name of the offline_fs_kbc flag
to fs rather than test. See https://github.com/confidential-containers/confidential-containers/issues/184 for reasoning behind this change.

Makefile: add more platforms to Makefile

---

attestation-agent/attester/src/bin/evidence_getter.rs
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/sample/mod.rs
attestation-agent/kbs_protocol/src/error.rs
attestation-agent/kbs_protocol/src/evidence_provider/native.rs
attestation-agent/lib/src/lib.rs

Rather than setting an environment variable to enable the sample attester, always enable it as a fallback.
See https://github.com/confidential-containers/confidential-containers/issues/184 for reasons 
I don't think it makes much sense to enable the sample attester based on an environment variable. Having it always available as a fallback shouldn't cause any security problems. The KBS/AS shouldn't be fooled by the sample evidence in a real deployment.

sample: always enable sample attester

---

attestation-agent/lib/src/token.rs
confidential-data-hub/kms/src/plugins/kbs/mod.rs

relates-to: https://github.com/confidential-containers/cloud-api-adaptor/issues/1637
Since peerpods will template the agent-config.toml with aa_kbc_params and /etc might be on a read-only volume, we need to make this path configurable.

aa/cdh: make agent-config path configurable by env

---

Cargo.lock
attestation-agent/coco_keyprovider/Cargo.toml
attestation-agent/coco_keyprovider/src/enc_mods/mod.rs
attestation-agent/coco_keyprovider/src/main.rs

cocokeyprovider: add support for daemonize

---

Cargo.lock
confidential-data-hub/storage/Cargo.toml
confidential-data-hub/storage/src/volume_type/alibaba_cloud_oss/oss.rs
ocicrypt-rs/src/keywrap/jwe.rs

The previous parameters of the function is not correct, s.t. using `source` as the target mount path. This commit fixes this.
Also, this commit leverages the async lib to handle filesystem and time operations to avoid blocking.
The last part is that in the previous version, all mount operations will share a same OSSFS_PASSWD_FILE and GOCRYPTFS_PASSWD_FILE path. This means that the operation cannot be idempotent. This is fixed by create a temp directory under /tmp for every mount operation to store those metadata files.
cc @LindaYu17 
related to https://github.com/kata-containers/kata-containers/pull/7965

Fixes mount parameter order in CDH/Storage/OSS

---

confidential-data-hub/Makefile
confidential-data-hub/README.md

Rename the feature flag to align with the feature and provide for build time customisations of the options
Fixes: #435

build: Rename the feature flag and set default

---

image-rs/scripts/build_confidential_data_hub.sh

We now use a explicit `none` for KMS_PROVIDER and RESOURCE_PROVIDER in the make file to tell no one will be builtin. In image-rs' integration test, only offline-fs-kbc will be used and that is builtin by default. Thus we do not need to add any extra KMS_PROVIDER or RESOURCE_PROVIDER.
See the context in
https://github.com/confidential-containers/guest-components/pull/437/commits/4e087429216a4806086d006835ca20a87b448a8a

image-rs: fix integration test

---

Cargo.lock
attestation-agent/kbc/src/lib.rs
attestation-agent/lib/Cargo.toml
attestation-agent/lib/src/aa_kbc_params.rs
attestation-agent/lib/src/lib.rs
attestation-agent/lib/src/token.rs
confidential-data-hub/kms/Cargo.toml
confidential-data-hub/kms/src/error.rs
confidential-data-hub/kms/src/plugins/kbs/mod.rs

In both AA and CDH there is duplicate logic to retrieve aa_kbc_params through various means. This change moves all related logic into a single place to guarantee consistency and make it easier to iterate on the way we retrieve aa_kbc_params (it is expected that the current approaches will be replaced by init_data in some fashion).
~Besides kernel cmdline and kata-agent config a third option that takes precedence over the other approaches has been added. This will help with testing, so we don't need to rely on the peerpod detection heurstic for that.~
Edit: will be replaced by an aa config-file, see discussion below
e.g. `AA_KBC_PARAMS=cc_kbc::http://localhost:8080 ./attestation-agent -a unix://tmp/aa-test.sock`
A dependency to `attestation_agent` has been added to the CDH/KMS project to …

aa_kbc_params: centralize handling in CDH and AA

---

Cargo.lock
Makefile
README.md
confidential-data-hub/hub/Cargo.toml
confidential-data-hub/hub/src/auth/mod.rs

`TEE_PLATFORM=all` to support a easy mode for users to build all guest components with all features enabled (including the attester plugins, etc)
`TEE_PLATFORM=amd` supports to build components of sev & snp.
Also, fixed a bug in CDH when both kbs and sev features are enabled. We not will initialize sev when `aa_kbc_param` is set to `sev`.

Makefile: support to build components for all platforms and amd

---

confidential-data-hub/kms/src/plugins/aliyun/annotations.rs

`AliSecretAnnotations` is some optional input parameters for `get_secret()` function of `Getter` in cdh/kms. With default value added, those who do not these parameters can pay no attention to them.

cdh/kms: add default value for "AliSecretAnnotations"

---

attestation-agent/coco_keyprovider/README.md
attestation-agent/docker/Dockerfile.keyprovider
attestation-agent/hack/encrypt-image.sh

The keyprovider docker image has been extended to bundle a keyprovider-capable skopeo and include a convenience script that simplifies the creation of encrypted images for usage in CoCo.
Documentation has been added to use the image.

keyprovider: extend docker image and documentation

---

Cargo.lock
attestation-agent/app/src/rpc/attestation/mod.rs
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/snp/hostdata.rs
attestation-agent/attester/src/snp/mod.rs
attestation-agent/attester/src/tdx/mod.rs
attestation-agent/attester/src/tdx/report.rs
attestation-agent/attester/src/utils.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent_ttrpc.rs
attestation-agent/lib/Cargo.toml
attestation-agent/lib/src/lib.rs
attestation-agent/protos/attestation-agent.proto

This new API is for kata-agent to check the data's integrity binding relationship with the hardware evidence.
Close #446 
The main work for TDX and SNP platform has been done by  @danmihai1 , this PR just refers most of the code.
cc @fitzthum

AA: Add API of CheckInitData

---

.github/workflows/aa_basic.yml
.github/workflows/aa_cc_kbc.yml
.github/workflows/image_rs_build.yml

The workflows use ubuntu-22.04 (ubuntu-latest) but install DCAP packages from focal.
While fixing that, also move away from deprecated apt-key usage and install recommended packages only.

ci: install DCAP packages from Jammy repo

---

Cargo.lock

Rustc 1.78.0-nightly (f067fd608 2024-02-05) was the latest nightly release, but it has a compatibility issue with
curve25519-dalek https://github.com/dalek-cryptography/curve25519-dalek/issues/618.
Now curve25519-dalek and x25519-dalek have a new release to fix the
issue. So we can update the dependencies about curve25519-dalek and
x25519-dalek.
Fixes: #470

Cargo.lock: Update dep of curve25519-dalek and x25519-dalek

---

attestation-agent/kbc/src/eaa_kbc/rats_tls/mod.rs

rats_tls_handle ptr should be correct initialized by extern C func rats_tls_set_verification_callback

Replace unsafe NonNull::new_unchecked with NonNull:new

---

image-rs/src/pull.rs
image-rs/src/resource/mod.rs
image-rs/src/signature/image/digest.rs

This PR attempts to fix these two rust nightly errors we started seeing:
```
Checking image-rs v0.1.0 (/home/porter/wo/confidential-containers/guest-components/image-rs)
error: trait `Protocol` is never used
--> image-rs/src/resource/mod.rs:33:7
|
33 | trait Protocol: Send + Sync {
|       ^^^^^^^^
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
error: direct implementation of `ToString`
--> image-rs/src/signature/image/digest.rs:79:1
|
79 | / impl ToString for Digest {
80 | |     fn to_string(&self) -> String {
81 | |         format!("{}:{}", self.algorithm, self.value)
82 | |     }
83 | | }
| |_^
|
= help: prefer implementing `Display` instead
= help: for further information visit …
```

CI: fix rust-nightly static checks

---

.github/workflows/aa_sample_keyprovider.yml
.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml
attestation-agent/app/src/rpc/keyprovider/message.rs
attestation-agent/app/src/rpc/keyprovider/mod.rs
attestation-agent/attester/src/tdx/mod.rs
attestation-agent/coco_keyprovider/src/enc_mods/crypto.rs
attestation-agent/coco_keyprovider/src/grpc/protocol/keyprovider_structs.rs
attestation-agent/lib/src/config/aa_kbc_params.rs
image-rs/src/auth/auth_config.rs
image-rs/src/bundle.rs
image-rs/src/config.rs
image-rs/src/decoder/mod.rs
image-rs/src/image.rs
image-rs/src/meta_store.rs
image-rs/src/pull.rs
image-rs/src/signature/image/digest.rs
image-rs/src/signature/image/mod.rs
image-rs/src/signature/mechanism/cosign/mod.rs
image-rs/src/signature/mod.rs
image-rs/src/signature/policy/mod.rs
image-rs/src/signature/policy/ref_match.rs
image-rs/src/stream.rs
image-rs/src/unpack.rs
ocicrypt-rs/src/keywrap/keyprovider/mod.rs

1. Fixes nightly lint error
2. Follow [the discussion](https://github.com/confidential-containers/confidential-containers/issues/193) from @portersrc , I fix the version of rust nightly compiler in GHA to avoid unexpected CI errors everytime new rust nightly version is released.

CI: Fix nightly lint error & fix rust nightly version

---

.github/workflows/image_rs_build.yml
image-rs/tests/image_decryption.rs

Add encrypted nydus image tests.

image-rs: add encrypted nydus image tests

---

.github/workflows/image_rs_build.yml

- Add building image-rs on s390x and powerpc64le
Note: At the moment this will probably fail with:
```
error: failed to run custom build command for `ring v0.16.20`
Caused by:
process didn't exit successfully: `/root/guest-components/target/debug/build/ring-f931d4c26d8deee2/build-script-build` (exit status: 101)
--- stderr
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ring-0.16.20/build.rs:358:10:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
whilst we wait for #422 to get fixed, so we shouldn't merge it until after that is fixed

image-rs: Add cargo build for multiarch

---

Cargo.lock
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/tdx/mod.rs

improve implementation of tdx runtime measurement API, 'extend_runtime_measurement'.
tdx attester should call intel DCAP lib api with the specified parameter type to avoid the high level needing to know the details of the hardware platform when calling the runtime measurement interface.

AA/attester: improve tdx runtime measurement

---

.github/workflows/aa_basic.yml
.github/workflows/cdh_basic.yml
Makefile

This makes the LIBC env could be overwritten for `all`, `tdx` and `amd` platforms.
Also update the ci workflow.
Related to https://github.com/kata-containers/kata-containers/pull/8870

Fix makefile

---

Makefile

echo command outside of recipe not valid, and results in:
```
Makefile:55: *** missing separator.  Stop.
```
, so replace with $(info)

Makefile: Fix error

---

Cargo.lock
confidential-data-hub/hub/Cargo.toml
confidential-data-hub/hub/src/bin/confidential-data-hub/config.rs

This commit gets rid of unwrap() in parsing CDH's config and will result in an error. Also, this commit adds support for a configuration file without any [[credentials]] array member.
To ensure the config behavior is as expected, adds some unit tests.
Fixes #514
cc @wainersm

CDH: fix config read

---

README.md
confidential-data-hub/README.md
confidential-data-hub/docs/RESOURCES_SERVICES.md

Sending a few improvements to the CDH docs:
* CDH: document the configuration heuristic
* CDH: document resources services
Cc @fitzthum @Xynnn007

Improve CDH docs

---

attestation-agent/attester/src/tdx/mod.rs

On DCAP 1.20, TDX attester will get report via dev `/dev/tdx_guest`, this is defined in
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/DCAP_1.20/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L52
btw, is `/dev/tdx-guest` used or it is a wrong name? cc @jialez0

AA/Attester: fix TDX platform detection

---

Cargo.lock
attestation-agent/attestation-agent/Cargo.toml
attestation-agent/attestation-agent/src/bin/grpc-aa/main.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/main.rs

Before this commit, AA will not enable log by default, so that the process will not print any output even if `RUST_LOG` env is set.

AA: add envlogger to enable log

---

image-rs/src/image.rs
image-rs/src/resource/kbs/mod.rs
image-rs/src/resource/kbs/native.rs

Currently image signature verification keys, auth files are got from confidential datahub who has a fixed ttrpc socket. So we do not require image-rs to have to configure the aa_kbc_params.
In Kata-CC this is important because in this way we can avoid parsing kernel cmdline in kata-agent.
Only when in enclave-cc, aa_kbc_params is still used by image-rs.

image-rs: refactor secure channel initialization logic

---

image-rs/src/decrypt.rs
image-rs/src/pull.rs
image-rs/tests/common/mod.rs
image-rs/tests/image_decryption.rs

The high level API of image-rs is `pull_image()`. There is one parameter named `decrypt_config` passed to the api, and the parameter is to specify the orignal kbc parameter, e.g.
provider:attestation-agent:offline_fs_kbc:null
However, different parts of the parameter is now specified
- `attestation-agent`: the key to look up keyprovider is embedded inside the encrypted image layer annotation.
- `offline_fs_kbc:null`: so-called AA_KBC_PARAMS, is defined in CDH if Kata-CC is used, so in this case, we do not to ensure the parameter is given as it will not be used. This is why we get rid of this parameter checking in this commit.
In enclave-cc scenarios, the `decrypt_config` is still used, and we will check the parameter in concrete `ocicrypt-rs`'s  `native` key provider plugin.

image-rs: get rid of checking `decrypt_config` parameter

---

confidential-data-hub/docs/kms-providers/alibaba.md

Building secret_cli without feature specified will generate a binary without functionality.

cdh/docs: bug fix - add build feature for aliyun

---

attestation-agent/attestation-agent/Cargo.toml
attestation-agent/attestation-agent/build.rs
attestation-agent/attestation-agent/src/bin/grpc-aa/main.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/main.rs
confidential-data-hub/hub/build.rs
confidential-data-hub/hub/src/bin/confidential-data-hub.rs

Fixes #530 
After this PR, the AA would show its built-in plugins by `-V` like the following
```
$ ./attestation-agent -V
attestation-agent 
Commit Hash: 083cb8750c325c7d90147f3bce1f498664e376fb (dirty)
Supported Attesters: TDX_ATTESTER, SGX_ATTESTER, AZ_SNP_VTPM_ATTESTER, AZ_TDX_VTPM_ATTESTER, SNP_ATTESTER
Token plugins: KBS, COCO_AS
```
and CDH
```
$ ./confidential-data-hub -V
confidential-data-hub 
Commit Hash: 083cb8750c325c7d90147f3bce1f498664e376fb (dirty)
Resource Providers: KBS, SEV
KMS plugins: ALIYUN, EHSM
```
Related to also #487 
cc @fitzthum @surajssd @mkulke

AA & CDH | Add feature information and git sha via `-V`

---

Cargo.lock
api-server-rest/src/aa.rs
api-server-rest/src/cdh.rs
api-server-rest/src/router.rs
attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/server.rs
confidential-data-hub/hub/protos/api.proto
confidential-data-hub/hub/src/bin/server/mod.rs
confidential-data-hub/hub/src/error.rs
confidential-data-hub/hub/src/hub.rs
confidential-data-hub/image/Cargo.toml
confidential-data-hub/image/src/annotation_packet/v1.rs
confidential-data-hub/image/src/annotation_packet/v2.rs
confidential-data-hub/image/src/error.rs
confidential-data-hub/image/src/lib.rs
confidential-data-hub/secret/Cargo.toml
confidential-data-hub/secret/src/bin/secret_cli.rs
confidential-data-hub/secret/src/error.rs
confidential-data-hub/secret/src/lib.rs
confidential-data-hub/secret/src/secret/layout/envelope.rs
confidential-data-hub/secret/src/secret/layout/vault.rs
confidential-data-hub/secret/src/secret/mod.rs
confidential-data-hub/storage/src/volume_type/aliyun/mod.rs

This PR does the following
1. Reorganize error handling and information in logs in CDH/AA. Only a brief error information will be responsed to caller, and detailed information will be printed in the log of CDH/AA. Close #541
2. ASR now will response an internal error (HTTP 500) when failed to execute API call. Close #529
3. Based on the code change, we bring out the duplicated code for `unseal_secret` in storage plugin

Optimize error for guest-components

---

Cargo.lock
attestation-agent/attestation-agent/Cargo.toml
attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/server.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/ttrpc_protocol/attestation_agent.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa/ttrpc_protocol/attestation_agent_ttrpc.rs
attestation-agent/attestation-agent/src/lib.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent.rs
attestation-agent/kbs_protocol/src/token_provider/aa/attestation_agent_ttrpc.rs
attestation-agent/protos/attestation-agent.proto

As discussed, this API is a workaround API for CoCo to apply initdata proposal. Once we agree on a better way (like systemd scheme), we can deprecate the API.
See https://github.com/kata-containers/kata-containers/issues/9468
cc @fitzthum

AA: add UpdateConfiguration API

---

Cargo.lock
api-server-rest/src/router.rs
attestation-agent/attestation-agent/src/lib.rs
confidential-data-hub/hub/src/bin/ttrpc_server/mod.rs
confidential-data-hub/storage/Cargo.toml
confidential-data-hub/storage/src/volume_type/aliyun/mod.rs
image-rs/src/bundle.rs
ocicrypt-rs/src/encryption.rs

Fix the bug that unexpected delete the remote OSS dir if it is writable.
also fix the log of ttrpc CDH.
cc @jialez0

CDH | Fix secure mount

---

image-rs/src/decoder/mod.rs

Images like `cgr.dev/chainguard/busybox` built using gzip directly might legitimately be using gzip multiple members. This really has to be supported to have broad compatibility with docker images as this style is prevalent in the distroless community.

Support gzip.multiple_members

---

image-rs/src/stream.rs
image-rs/src/unpack.rs

This is necessary to support images using non-root users and a mixture of runtime users.

Gzip should preserve ownership/permissions

---

Cargo.lock
image-rs/Cargo.toml
image-rs/src/unpack.rs

When looking at the resulting file contents of multilayer image we frequently are seeing `.wh.` files. We need to correctly handle whiteouts. See
1) https://github.com/opencontainers/image-spec/blob/main/layer.md#whiteouts
2) https://github.com/containerd/containerd/blob/v1.7.17/archive/tar_opts_linux.go#L34

Handle gzip whiteouts correctly

---

.github/workflows/aa_basic.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml
confidential-data-hub/secret/src/bin/secret_cli.rs

The following workflows are enabled by a self-hosted runner named `s390x-runner-01` registered to the `coco` org:
- attestation agent
- confidential data hub
- API server rest
- image-rs
`ocicrypt-rs` is not included for the enablement this time because a base build image `runetest/compilation-testing` does not support s390x.
The changes are verified via a private runner:
- AA: https://github.com/BbolroC/cc-guest-components/actions/runs/9451193780
- CDH: https://github.com/BbolroC/cc-guest-components/actions/runs/9450832623
- API server rest: https://github.com/BbolroC/cc-guest-components/actions/runs/9450572957
- image-rs: https://github.com/BbolroC/cc-guest-components/actions/runs/9453177410
This PR will enable the community to run tests natively for each component.
The rationale for a …

Enable basic CI for s390x

---

.github/workflows/aa_basic.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml

It is observed that some packages (e.g. docker) are required to run workflows for s390x. Like the post-action, we need to place pre-action for the platform.

GHA: Place pre-action for s390x self-hosted runner

---

.github/workflows/aa_basic.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml
image-rs/src/image.rs

This commit fixes the wrongly indented configuration in #585 and place the pre action step after the code check-out.
There is an issue on pulling an image `mcr.microsoft.com/hello-world` on s390x.
It looks a load balancer for the microsoft registry is unstable so that the runner was able to pull the image with 10& success ratio (see https://github.com/microsoft/containerregistry/issues/144)
It is not reasonable to let the test run under the unstable environment.
This commit skips the tests at image.rs for the platform.

GHA: Fix indentation error and skip image.rs tests for s390x

---

.github/workflows/aa_occlum_sgx.yml

Now we are using a ACTIONS_RUNNER_HOOK_JOB_COMPLETED ability provided by github action. This allows us not to explicitly define a post-run script in yaml. The post actions are defined onside the runner itself.
See documents: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/running-scripts-before-or-after-a-job#triggering-the-scripts
cc @mythi

ci: update occlum ci

---

attestation-agent/attestation-agent/src/config/aa_kbc_params.rs
attestation-agent/attestation-agent/src/config/coco_as.rs
attestation-agent/attestation-agent/src/config/kbs.rs
confidential-data-hub/hub/src/bin/config/mod.rs
confidential-data-hub/hub/src/bin/grpc-cdh.rs
confidential-data-hub/hub/src/bin/ttrpc-cdh.rs
confidential-data-hub/kms/src/plugins/kbs/mod.rs

CDH should firstly read config specified with commandline, and then env.
aa_kbc_param should be firstly read directly from CDH's config file. If there is no config file, try to read from env and then kernel cmdline. If still no values found, use a default one with offline_fs_kbc.
Close #593
cc @huoqifeng @mkulke

CDH: fix aa_kbc_params and config reading

---

attestation-agent/attestation-agent/src/config/aa_kbc_params.rs
attestation-agent/attestation-agent/src/config/coco_as.rs
attestation-agent/attestation-agent/src/config/kbs.rs
attestation-agent/attestation-agent/src/config/mod.rs
attestation-agent/attestation-agent/src/lib.rs
confidential-data-hub/hub/src/bin/config/mod.rs

Before this commit, if no configuration and proper aa_kbc_param given to AA, the launch of AA will panic.
This commit will use a default value for aa_kbc_param for AA/CDH. If no env or kernel cmdline, default value offline_fs_kbc and null will be used. If a aa_kbc_param is specified, it will be parsed as kbc:url. If the aa_kbc_param is malwared, the launch process will still fail.
cc @mkulke

AA: fix launch configuration

---

Cargo.lock
image-rs/Cargo.toml
image-rs/src/unpack.rs

Revert whiteout handling whilst we investigate image pull errors with whiteouts that seemed to start here
This reverts commit a54646f4dd544128328bed3be0a6a3dde9fcd1a5.

Revert "Handle gzip whiteouts correctly"

---

Cargo.lock
Cargo.toml
attestation-agent/attester/Cargo.toml
image-rs/Cargo.toml
image-rs/src/stream.rs
image-rs/src/unpack.rs

before this commit, tar reader is sync, thus we need a separate os thread for every image layer pulling green thread. This would cost more memory and CPU resource because on linux a thread actually means another process.
This commit replace the tar crate to async version, thus we do not need another thread to handle this to decrease memory occupation.
Also, the original thread way would make the error of `unpack()` function missing because it would not be captured by original thread. Thus always a inclear `Send Error {...}` error message will be returned. The new way will not face such situation. cc @stevenhorsman 
Some abilities like permission maintain, ownership maintain are manually implemented as the original crate does not support well.
cc @arronwy

image-rs: make tar reader async

---

Cargo.lock
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/az_snp_vtpm/mod.rs
attestation-agent/attester/src/az_tdx_vtpm/mod.rs

the trait fn's extend_runtime_measurement() have been implemented for both az-snp-vtpm and az-tdx-vtpm. There is a bit of duplicate code, but it's better than introducing dependencies across attesters.

attester: implement runtime measurement for az vtpm TEEs

---

Cargo.lock
attestation-agent/attestation-agent/src/config/mod.rs
attestation-agent/attestation-agent/src/lib.rs

For the extend runtime measurement op we currently have 2 defaults, one hardcoded and one specified in the configuration file.
Only the initial extend operation will use the PCR in the config, if called via an API (w/o specifying a concrete register) the extend op will default to the hardcoded instead of the value specified in the config file.
This behaviour implies that the caller of the RPC method has knowledge about the internals of the TEE (valid PCR registers), which is unfortunate (would need a kata-agent config, for example)
This PR consolidates the algo to pick a PCR for all extend ops:
1) PCR specified in the call
2) PCR specified in config file
3) Hardcoded default PCR
Drive-by fix: Cargo.lock update

AA: fallback to pcr in configfile in extend operations

---

attestation-agent/attestation-agent/src/eventlog.rs
attestation-agent/attestation-agent/src/lib.rs

The NELR spec doesn't prescribe a format for the `content` payload of an event. However, since a line break is semantic in the log file, the content cannot be a multi-line string:
```
content = "one two\nthree four five"
|
v
my-domain my-operation one two
three four five
```
The result would be ambiguous. This change enforces this assertion. Also added tests for the event log and moved the init log line generation to the eventlog module (as the digest calc is already there).

AA: handle multiline content in log events

---

image-rs/src/image.rs

The current behavior of switching to anonymous authentication does hide the error to get the credentials. So changed the logic to bail out in case of error.

image-rs: bail out if unable to get registry auth credentials

---

confidential-data-hub/docs/SECURE_STORAGE.md
confidential-data-hub/docs/use-cases/secure-mount-with-block-device.md
confidential-data-hub/storage/Cargo.toml
confidential-data-hub/storage/scripts/luks-encrypt-storage
confidential-data-hub/storage/src/error.rs
confidential-data-hub/storage/src/volume_type/blockdevice/error.rs
confidential-data-hub/storage/src/volume_type/blockdevice/luks/mod.rs
confidential-data-hub/storage/src/volume_type/blockdevice/mod.rs
confidential-data-hub/storage/src/volume_type/mod.rs

Support to encrypt block device in cdh.
Fixed: #540 -- part II

cdh: support to encrypt block device

---

confidential-data-hub/storage/scripts/luks-encrypt-storage

Added the `-u` flag to the mktemp command to generate a random name without creating a file in the `luks-encrypt-storage` script. This change ensures that mktemp only produces a unique name, which can be used as an opened device name without the side effect of file creation.
Example usage:
opened_device_name=$(mktemp -u "encrypted_disk_XXXXX")
This update improves the script by preventing unnecessary file creation and potential errors related to file system permissions or read-only states.

cdh:storage: Add `-u` flag to mktemp to avoid file creation

---

Cargo.lock
confidential-data-hub/kms/src/plugins/aliyun/client/client_key_client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/ecs_ram_role_client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/sts_token_client/mod.rs

Change get_secret() function of AliyunKmsClient::ClientKey, AliyunKmsClient::EcsRamRole, and AliyunKmsClient::StsToken into immutable form. And also separate them with Getter trait.

cdh/kms: modify get_secret() function

---

image-rs/src/config.rs
image-rs/src/decoder/mod.rs
image-rs/src/image.rs
image-rs/src/meta_store.rs

Support to write `meta_store` to `meta_store.json`.
Set the absolute path for meta store with `meta_store.json`

image-rs: Support to reuse meta_store

---

attestation-agent/deps/crypto/src/lib.rs
attestation-agent/kbs_protocol/src/client/mod.rs
confidential-data-hub/hub/src/auth/kbs.rs
confidential-data-hub/kms/src/api.rs
image-rs/src/resource/kbs/mod.rs
image-rs/src/signature/mechanism/cosign/mod.rs
image-rs/src/signature/mechanism/simple/sigstore.rs
image-rs/src/signature/policy/policy_requirement.rs

The CI builds for 'stable' now point to Rust 1.80.0 and some linter checks started failing with the newly added check for doc_lazy_continuation.

ci: fix doc_lazy_continuation findings with Rust 1.80.0

---

attestation-agent/attestation-agent/src/config/mod.rs
attestation-agent/attestation-agent/src/lib.rs

On most platforms, runtime measurement is now not supported. Thus the init PCR extension will fail.
This commit adds a flag for AA launch config to control whether eventlog is enabled. By default it will be closed.
In future, with initdata, the deployer would specify whether to enable eventlog in AA's config.
fixes #626
cc @ChengyuZhu6 
cc also @arronwy

AA: add flag to enable eventlog

---

ocicrypt-rs/src/encryption.rs

The error for encryption::pre_unwrap_key() is silently discarded, which means we get no meaningful error in consumers, like the kata-agent log on ttrpc connectivity problems. I don't think it makes sense to not abort on errors from pre_unwrap_key.

ocicrypt-rs: dont't swallow pre_unwrap_key() error

---

.github/dependabot.yml

the default value for open-pull-requests-limit is 5, to avoid block by some PR may need rebase source code, change the value from 1 to 3

ci: increase open-pull-requests-limit from 1 to 3

---

.github/workflows/aa_basic.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml

The following hooks:
- ACTIONS_RUNNER_HOOK_JOB_STARTED
- ACTIONS_RUNNER_HOOK_JOB_COMPLETED
could perfectly replace the existing {pre,post}-action scripts and will make a workflow independent of the runner context. This PR wipes out all GHA steps where the actions are triggered.

GHA: Remove {pre,post}-action steps for self-hosted runners

---

.github/workflows/aa_cc_kbc.yml
.github/workflows/aa_crypto.yml
.github/workflows/aa_eaa_kbc.yml
.github/workflows/aa_sample_keyprovider.yml
.github/workflows/aa_sev_kbc.yml

This PR considers the following:
- <del>Stop redundant checks after PR merge</del> (thanks to #644)
- Introduce concurrency.cancel-in-progress
You can find the detailed explanation in each commit message.

GHA: Introduce cancel-in-progress

---

.github/workflows/aa_basic.yml
.github/workflows/aa_cc_kbc.yml
.github/workflows/aa_crypto.yml
.github/workflows/aa_eaa_kbc.yml
.github/workflows/aa_occlum_sgx.yml
.github/workflows/aa_sample_keyprovider.yml
.github/workflows/aa_sev_kbc.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml

Despite #644, duplicate checks are still being triggered post-merge. The following condition seemed intuitive:
- github.event_name != 'push' || github.event.pull_request.merged == false
But it turns out that `pull_request.merged` is still false on merge, which allows the job to proceed. 
(see https://github.com/BbolroC/cc-guest-components/actions/runs/10215060610/workflow)
This commit focuses solely on `github.event_name != 'push'`, which is true on merge. 
(see https://github.com/BbolroC/cc-guest-components/actions/runs/10215137827/workflow)

GHA: Fix condition for duplicate checks post-merge

---

Cargo.lock
attestation-agent/deps/resource_uri/Cargo.toml
attestation-agent/deps/resource_uri/src/lib.rs
attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/src/client/token_client.rs

With this change, the kbs-client is able to send a get-resource request that includes the query string provided e.g.:
kbs-client --url http://127.0.0.1:8080 \
get-resource \
--path 'plugin/nebula/credential?ip[ip]=10.11.12.13&ip[netbits]=21&name=pod1'
This is required by the KBS repository plugin interface.

attestation-agent: Extend ResourceUri to support query string

---

Cargo.lock
Cargo.toml
attestation-agent/kbs_protocol/src/client/mod.rs
attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/src/error.rs
attestation-agent/kbs_protocol/src/keypair.rs

Pull in @Xynnn007's work for https://github.com/confidential-containers/trustee/issues/242#issuecomment-2146864188

Improve KBS protocol version handling and bump the version to v0.1.1 due to kbs-types changes

---

image-rs/src/signature/mechanism/cosign/mod.rs

This commit deletes a duplicated unit case for cosign signature scheme.
Also, the original cosign signed test image is based on busybox, thus a successfully pulling for that image (busybox) via nydus-snapshotter would cause another pulling with policy preventing the image successful. This is because of some logic inside nydus-snapshotter.
To handle this, we update the signed image to be a different one from busybox. Separately we will fix this on the snapshotter side.
cc @stevenhorsman

image-rs: update cosign signature verification unit test

---

confidential-data-hub/storage/scripts/luks-encrypt-storage

While reviewing https://github.com/kata-containers/kata-containers/pull/9999 I wanted to understand confidential-data-hub/storage/scripts/luks-encrypt-storage better so I took a deep look at this file. I began to worry whether the logic to detect the blocks could fail or not, and in case of failure if it should continue the script as if everything went well (possible not cleaning up the block pages if any). Is it concern? So I decided to add a check for the block numbers, that if empty then the script bails out. Let me know if it is wrong and will introduce another issue that I could anticipate.
While in here, I delinted the script. 
Cc @Xynnn007 @ChengyuZhu6 @fitzthum

cdh: improves the luks-encrypt-storage script

---

.github/workflows/image_rs_build.yml
Cargo.lock
image-rs/Cargo.toml
image-rs/src/auth/auth_config.rs
image-rs/src/auth/mod.rs
image-rs/src/decoder/mod.rs
image-rs/src/decrypt.rs
image-rs/src/image.rs
image-rs/src/nydus/service.rs
image-rs/src/nydus/utils.rs
image-rs/src/pull.rs
image-rs/src/signature/image/mod.rs
image-rs/src/signature/mechanism/cosign/mod.rs
image-rs/src/signature/mechanism/mod.rs
image-rs/src/signature/mechanism/simple/mod.rs
image-rs/src/signature/mechanism/simple/sigstore.rs
image-rs/src/signature/mechanism/simple/verify.rs
image-rs/src/signature/mechanism/simple/xrss.rs
image-rs/src/signature/mod.rs
image-rs/src/signature/payload/simple_signing.rs
image-rs/src/signature/policy/mod.rs
image-rs/src/signature/policy/policy_requirement.rs
image-rs/src/signature/policy/ref_match.rs
ocicrypt-rs/src/encryption.rs

This release contains a security fix for confidential pulling of unsigned images: https://github.com/oras-project/rust-oci-client/pull/152. 
The upgrade is not trivial, because the crate has been renamed (https://github.com/oras-project/rust-oci-client/issues/142) and there are breaking changes:
* https://github.com/oras-project/rust-oci-client/issues/157
* https://github.com/oras-project/rust-oci-client/pull/121
Thus, I converted all annotation values from `HashMap` to `BTreeMap`, worked around the `sigstore::registry::Auth` conversion not being implemented for the new crate, and am now passing the  stream wrapped by `SizedStream`.

deps: upgrade oci-distribution to v0.12.0

---

.github/workflows/aa_release.yml
attestation-agent/coco_keyprovider/README.md

As the original  repo is now archived, thus we havenot been able to publish the coco keyprovider image for a long time. This commit fixes this issue by changing the image repo.
Fixes #672

ci: fix the CoCoKeyprovider image pushing logic

---

attestation-agent/docker/Dockerfile.keyprovider

The dependency on skopeo is quite fragile as there are several versions of the project that would generate an encrypted image with a gzip header that Confidential Containers simply cannot deal with.
For now, let's use f64a376, from Aug 14th 2024 as, empirically, we know that it works.
We must have tests implemented in order to cover the documentation we provide, and whether it works or not.

keyprovider: Pin a specific version of skopeo

---

confidential-data-hub/storage/scripts/luks-encrypt-storage

Use --batch-mode in luksFormat command.
This change improves the script by eliminating the need for echoing "YES", making it more streamlined and efficient.

cdh:storage: Refactor luksFormat command to use --batch-mode

---

README.md

It always takes me a while to find the CoCo keyprovider since it is in the attestation-agent dir. Let's add it to the tools section, which lists all the tools provided in this repo. We might also think about moving the keyprovider itself at some point.

docs: add coco_keyprovider to tools section

---

Cargo.lock
image-rs/Cargo.toml
image-rs/src/unpack.rs

Some platforms/file-systems do not support xattrs, this would make the image pull fail because of failing to set xattr. This commit will check whether the target path supports xattr. If yes, the unpacking will maintain xattrs; if not, it will not set xattrs.
Fixes #690

image-rs: check xattrs for target dir when image unpacking

---

confidential-data-hub/golang/README.md
confidential-data-hub/golang/cmd/grpc-client/main.go
confidential-data-hub/golang/cmd/ttrpc-client/main.go
confidential-data-hub/golang/pkg/core/common.go
confidential-data-hub/golang/pkg/grpc/api_grpc.go
confidential-data-hub/golang/pkg/grpc/api_grpc_test.go
confidential-data-hub/golang/pkg/grpc/mock/mock_grpc.go
confidential-data-hub/golang/pkg/ttrpc/api_ttrpc.go
confidential-data-hub/golang/pkg/ttrpc/api_ttrpc_test.go
confidential-data-hub/golang/pkg/ttrpc/mock/mock_ttrpc.go

Add support for SecureMount in the go client tool.

cdh:golang: Add support for SecureMount in the go client tool

---

image-rs/Cargo.toml
image-rs/src/unpack.rs

This PR readds whiteout handling on platforms that support xattr
Fixes: #604

image-rs: Handle gzip whiteouts correctly

---

attestation-agent/attester/src/az_tdx_vtpm/mod.rs

Changed evidence generation method which will include report_data in re-generated HCL report (azTdxVtpm)
Signed-off-by: Pawel Proskurnicki <pawel.proskurnicki@intel.com>

AA: use enhanced version of vtpm get report for ITA

---

Cargo.lock
image-rs/Cargo.toml

The new version of krata-tokio-tar supports long link name.
Fixes #689
cc @bpradipt @JakubLedworowski

dep: update krata-tokio-tar to v0.4.2

---

Cargo.lock
attestation-agent/attestation-agent/Cargo.toml
attestation-agent/attestation-agent/src/config/mod.rs
attestation-agent/attestation-agent/src/eventlog.rs
attestation-agent/deps/crypto/src/algorithms.rs
attestation-agent/deps/crypto/src/lib.rs
attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/src/error.rs

Add a `supported-hash-algorithms` list to the `Request` to allow the
returned `Challenge` to select an appropriate TEE-specific algorithm
from the list.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

AA: kbs: Add supported hash algorithms to Request

---

.github/workflows/vendor_release.yml

Currently we're not publishing the vendored code as part of the release, which leads to all the downstream which do not have access to internet whilst building their components to do this process manually.
Let's be nice to the downstreams, let's publish the vendors ourselves.
Here's one release that I cut, on my own branch, showing the result of this action: https://github.com/fidencio/guest-components/releases/tag/v0.0.0-test-vendored-tarball

release: Publish vendored code

---

Cargo.lock
Makefile
attestation-agent/attestation-agent/Cargo.toml
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/cca/mod.rs
attestation-agent/attester/src/lib.rs
attestation-agent/attester/src/tsm_report/mod.rs

The latest Arm CCA Linux guest support (see `cca-guest/v2` and `cca-guest/v3` branches in https://gitlab.arm.com/linux-arm/linux-cca) have added support for TSM Reports ABI.

AA: Update CcaAttester to use TSM Report ABI

---

attestation-agent/deps/crypto/src/algorithms.rs
attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/src/error.rs

Create a new error to handle the scenario where the RCAR JSON specifies the selected hash algorithm
using the wrong data type (any type other than 'string').
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

AA: kbs: Improve handling of invalid RCAR JSON

---

attestation-agent/attester/src/sgx_dcap/mod.rs
attestation-agent/coco_keyprovider/src/grpc/mod.rs
attestation-agent/kbs_protocol/src/builder.rs
attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/src/client/token_client.rs
attestation-agent/kbs_protocol/src/evidence_provider/native.rs
attestation-agent/kbs_protocol/src/token_provider/aa/mod.rs
confidential-data-hub/hub/src/auth/kbs.rs
confidential-data-hub/hub/src/bin/ttrpc_server/mod.rs
confidential-data-hub/hub/src/config.rs
confidential-data-hub/hub/src/hub.rs
confidential-data-hub/image/src/annotation_packet/v2.rs
confidential-data-hub/image/src/lib.rs
confidential-data-hub/kms/src/plugins/aliyun/client/client_key_client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/ecs_ram_role_client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/mod.rs
confidential-data-hub/kms/src/plugins/aliyun/client/sts_token_client/mod.rs
confidential-data-hub/kms/src/plugins/ehsm/client.rs
confidential-data-hub/kms/src/plugins/kbs/cc_kbc.rs
confidential-data-hub/kms/src/plugins/kbs/mod.rs
confidential-data-hub/kms/src/plugins/kbs/offline_fs.rs
confidential-data-hub/kms/src/plugins/kbs/sev/client.rs
confidential-data-hub/storage/src/volume_type/aliyun/mod.rs
confidential-data-hub/storage/src/volume_type/blockdevice/mod.rs
image-rs/src/resource/kbs/native.rs
image-rs/src/unpack.rs
ocicrypt-rs/src/keywrap/keyprovider/mod.rs

Please see the commit message of this PR.
cc @stevenhorsman

Fix configuration file default value and make error information more detailed

---

attestation-agent/Makefile

CDH already does this and ASR doesn't work with GRPC. This change shouldn't break any existing invocations of the makefile with ttrpc=true, only builds that rely on grpc being implicitly picked. Due to the CDH's default and ASR being ttrpc-only I don't think we break anything downstream.

attestation-agent: default to ttrpc in Makefile

---

attestation-agent/attestation-agent/config.example.json
attestation-agent/attestation-agent/config.example.toml

add flag 'enable_eventlog' to aa example config according to the related PR: #627

attestation-agent: add flag 'enable_eventlog' to aa example config

---

.github/actions/install-intel-dcap/action.yml
.github/workflows/aa_basic.yml
.github/workflows/aa_cc_kbc.yml
.github/workflows/image_rs_build.yml
.github/workflows/publish-artifacts.yml
Makefile

Pushing artifacts as binaries to the project's GHCR. The build job is split between AA and CDH+ASR. AA has specific build and runtimerequirements depending on the TEE, while the CDH+ASR are generic per arch.
Hence $AA is tagged with $sha-$tee ($arch is implicit in $tee) while CDH+ASR are tagged with $sha-$arch.
Peerpod as a downstream project currently builds GC binaries as part of their pipeline. This is rather costly, the project is written in golang and needs to maintain a complex rust build infra for GC that often drifts in terms of rust-versions, feature-toggles and makes it hard to keep up to date with recent GC. There's also considerable overhead in terms of build-time.
It makes sense to have canonical cache of build-artifacts that can be consumed downstream.

CI: Publish binaries with ORAS

---

attestation-agent/docs/IMAGE_ENCRYPTION.md

This PR fixes a misspelling in the IMAGE ENCRYPTION document.

docs: Fix misspelling in IMAGE ENCRYPTION document

---

.github/workflows/publish-artifacts.yml

`oras-project/setup-oras` (raised by #731) does not support s390x like:
```
Error: Error: unsupported architecture: s390x
```
https://github.com/confidential-containers/guest-components/actions/runs/11223420868/job/31198020471
https://github.com/confidential-containers/guest-components/actions/runs/11223420868/job/31198020098
But the package is already installed and maintained by the self-hosted runner admin.
Let's skip installing it for the platform.

gha: Do not use oras-project/setup-oras for s390x

---

.github/workflows/publish-artifacts.yml

We missed the 2nd invocation of setup-oras in the prior PR #739
CDH and ASR builds do not need to setup oras on s390x self-hosted runners, since the setup is currently broken and it's provided on the self-hosted runners anyway.

ci: skip oras setup for s390x builds

---

.github/workflows/publish-artifacts.yml

For CDH, the skipping condition for ORAS on s390x must have been
`if: matrix.arch != 's390x'` instead of `if: matrix.platform.arch != 's390x'`

gha: Fix condition for skipping ORAS installation on s390x

---

.github/workflows/publish-artifacts.yml

The matrix parameters were not properly referenced and the tag variable wasn't referencing the TEE_PLATFORM for the AA publish job.

ci: fix multi-arch oci publish for AA

---

README.md
confidential-data-hub/Makefile
confidential-data-hub/README.md
confidential-data-hub/hub/Cargo.toml
confidential-data-hub/hub/src/bin/cdh-oneshot.rs

One-shot CDH is a different version of CDH that will run and do the operation one time then exit. This is useful in scenarios where CDH cannot run as a long term daemon.

CDH | add one-shot CDH

---

image-rs/docs/image_auth.md

This PR fixes a misspelling in image auth documentation.

docs: Fix misspelling in image auth documentation

---

attestation-agent/kbs_protocol/test/kbs-config.toml

client::rcar_client::test::test_client pulls kbs:latest image for tests but the local kbs-config.toml is oudated and tests won't run.
Update the config to get CI tests passing again.

kbs_protocol: update KBS config for test_client tests

---

Cargo.lock
attestation-agent/attester/Cargo.toml

Support building with openssl 3

Bump csv-rs for openssl 3 support

---

confidential-data-hub/README.md
confidential-data-hub/kms/Cargo.toml
confidential-data-hub/kms/src/plugins/ehsm/README.md

eHSM crate is no longer maintained and archived. Also, it requires openssl to be built thus cannot be built with musl.
This patch removes it from default features of `kms` crate. If one wants to build CDH with eHSM support, `KMS_PROVIDER=ehsm` can be used when executing Makefile of CDH.

CDH/KMS: remove ehsm from defaut features

---

attestation-agent/attestation-agent/src/token/coco_as.rs

The API should include `policy_ids` (which will be parsed on the CoCoAS side into `default` if no value is given). Also, `tee_type` being serialized would contain extra `"` chars.

AA: fix CoCoAS Token getter

---

.github/workflows/trustee-attester.yml
attestation-agent/kbs_protocol/Cargo.toml
attestation-agent/kbs_protocol/src/bin/trustee-attester/README.md
attestation-agent/kbs_protocol/src/bin/trustee-attester/main.rs

The trustee attester is a tool to attest and fetch secrets from Trustee.
Trustee attester is using attestation-agent's kbs_protocol client and attesters to gather hardware-based confidential-computing evidence and send it over to Trustee.
This PR replaces #755. Binary renamed and moved under kbs_protocol.
Also Trustee URL and optional certificate are given in the command line and not in a configuration file.

Add trustee-agent - a simple tool to fetch secrets from Trustee

---

.github/workflows/aa_basic.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml

This will also set up build cache and is consistent with the AA CI workflow.

ci: use rustlang gh wf to install rust in cdh/aa/asr ci

---

Cargo.lock
attestation-agent/kbs_protocol/test/kbs-config.toml

This patch updates the kbs config due to https://github.com/confidential-containers/trustee/pull/553
cc @mythi

AA | Fix kbs_client test config

---

attestation-agent/kbs_protocol/src/client/rcar_client.rs
attestation-agent/kbs_protocol/test/kbs-config.toml
attestation-agent/kbs_protocol/test/policy.rego

Due to the EAR PR, the configuration file format has been changed a little. This patch updates the KBS configuration file to include the latest EAR checking logic.

CI | Fix Kbs Client Error due to KBS configuration for EAR

---

image-rs/src/image.rs
image-rs/src/pull.rs

Before this commit, when we pull images who have two encrypted layers whose corresponding plaintext layers are same. For example `quay.io/fidencio/prueba:encrypted`, there will be an error like
```
index out of bounds: the len is 25 but the index is 25
```
This is caused by the deduplication logic inside image pull logic. On one hand, it will delete duplicated layers recorded inside image manifest, who reflectes the encrypted layers/blobs. On the other hand, it will delete duplicated layers recorded inside the config.json, who reflects the plaintext of the layers.
The image encryption logic will generate a random symmetric key for each layer. Thus even the same plaintext layer would be encrypted into different blobs/layers. Thus after deduplication, we might have more layers for image …

image-rs: fix duplicated image layer detective logic

---

image-rs/src/config.rs

I said I would update these comments back when we refactored the config file and now I have finally done it.
No functional changes. Hopefully this helps. These comments are fairly important because they describe a couple of features that aren't widely documented.

images-rs: clarify comments in image config file

---

.github/workflows/publish-artifacts.yml

Publishing arm64 artifacts to the project's GHCR using cross-compilation. This is an interim step. The native compilation will be introduced when arm runner is set up for CI.
`publish-artifacts` workflows are executed in my forked repo. except s390x architecture. (https://github.com/seungukshin/guest-components/actions/runs/12298710877)

ci: publish arm64 artifacts

---

attestation-agent/coco_keyprovider/README.md

Minor doc tweak. Resolves #702

Update docs to point to correct coco-keyprovider

---

image-rs/src/image.rs

A Rust 1.84.0 toolchain will complain about unused lifetime annnotations.

image-rs: removed unused lifetime annotation

---

image-rs/tests/README.md

I can't remember if we ever had a separate image-rs repo. Either way, our link checker has recently started complaining about this, and indeed the link doesn't exist.

image-rs: fix broken link

---

.github/workflows/aa_basic.yml
.github/workflows/aa_cc_kbc.yml
.github/workflows/aa_crypto.yml
.github/workflows/aa_release.yml
.github/workflows/aa_sample_keyprovider.yml
.github/workflows/api-server-rest-basic.yml
.github/workflows/cdh_basic.yml
.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml
.github/workflows/trustee-attester.yml
attestation-agent/Makefile
attestation-agent/docker/Dockerfile.keyprovider

This changes enables CI tests on arm64 runner.
Ther guest-components's CI is as following: (${\color{red}red}$ parts are added by this change, links are test results on forked repo.)
* aa_basic.yml (on amd64, s390x, ${\color{red}arm64}$)
* https://github.com/seungukshin/guest-components/actions/runs/12910598245/job/36000990431
* aa_cc_kbc.yml (on amd64, ${\color{red}arm64}$)
* https://github.com/seungukshin/guest-components/actions/runs/12910903728/job/36002045320
* aa_crypto.yml (on amd64, ${\color{red}arm64}$)
* https://github.com/seungukshin/guest-components/actions/runs/12928771208
* aa_occlum_sgx.yml (on amd64)
* aa_release.yml (on amd64, but generate amd64, ${\color{red}arm64}$ image using docker-buildx)
* https://github.com/seungukshin/guest-components/actions/runs/12928098948/job/3 …

ci: Enable ci tests on arm64

---

Cargo.lock
image-rs/Cargo.toml
image-rs/src/unpack.rs

astral-tokio-tar is a fork version of krata-tar-rs, and it introduces more bug fixes and features than krata-tar-rs, including the long link bug #689.
Also, the mtime preserving is added to astral-tokio-tar itself, thus we do not to do this explicitly.
Close #689
cc @arronwy @ChengyuZhu6 @burgerdev

image-rs: replace krata-tar-rs to astral-tokio-tar

---

Cargo.lock
image-rs/Cargo.toml

`oci-client/rustls-tls-native-roots` feature will allow oci-client to read local CA certs including self-signed certs in the rootfs when using rustls suites.
Before this patch, if we pull an image with `kata-cc-rustls-tls` feature from self-signed registry whose CA is updated with `update-ca-certificates`, there will be an error
```
failed to pull manifest error sending request for url (https://127.0.0.1:5000/v2/alpine/manifests/latest)
```
With this patch it will succeed.

image-rs: enable rustls-native-certs when using rustls

---

Cargo.lock
Cargo.toml
attestation-agent/attestation-agent/src/token/kbs.rs
attestation-agent/deps/crypto/Cargo.toml
attestation-agent/deps/crypto/src/asymmetric.rs
attestation-agent/deps/crypto/src/native/aes256ctr.rs
attestation-agent/deps/crypto/src/native/aes256gcm.rs
attestation-agent/deps/crypto/src/native/ec.rs
attestation-agent/deps/crypto/src/native/mod.rs
attestation-agent/deps/crypto/src/native/rsa.rs
attestation-agent/deps/crypto/src/rust/aes256ctr.rs
attestation-agent/deps/crypto/src/rust/aes256gcm.rs
attestation-agent/deps/crypto/src/rust/ec.rs
attestation-agent/deps/crypto/src/rust/mod.rs
attestation-agent/deps/crypto/src/rust/rsa.rs
attestation-agent/deps/crypto/src/symmetric.rs
attestation-agent/kbs_protocol/src/builder.rs
attestation-agent/kbs_protocol/src/client/mod.rs
attestation-agent/kbs_protocol/src/keypair.rs
attestation-agent/kbs_protocol/src/token_provider/aa/mod.rs

~Per RFC7516, the AEAD's auth tag should be included inside the JWE body. We fix this to align with trustee side~
https://github.com/confidential-containers/trustee/pull/597
~~Let's wait after https://github.com/confidential-containers/trustee/pull/597 gets merged.~~
This patch does a bunch of fixes per RFC7516.
1. AEAD Auth Tag is now expcilitly included inside the `tag` part.
2. Add TEE key pair support for `RSA OAEP` and `ECDH-ES+A256KW`(by default)
3. Mark `RSA PKCS#1 v1.5` padding scheme as deprecated as it is not recommended.

AA/kbs_protocol: Update to 0.2.0 to fix JWE decryption logic due to RFC7516

---

attestation-agent/kbs_protocol/build.rs
confidential-data-hub/hub/build.rs
image-rs/build.rs

Currently if we clone the repo and issue `make` from `confidential-data-hub`, the `build` target fires, which runs this:
```cd hub && $(RUST_FLAGS) cargo build $(release) --no-default-features --features "$(features)" $(binary) $(LIBC_FLAG)```
During normal development, repeatedly running this command will take ~10s. This is because the build.rs scripts are designed to produce .rs files from .proto files, which causes cargo to see dirty/stale .rs source and thus rebuild. This PR only triggers those build.rs steps when the proto files change. This should reduce that normal development flow (i.e. `make` from `confidential-data-hub/`) to the expected 0.5s.

[Build] Stop build.rs from triggering due to protoc output for hub

---

.github/workflows/cdh_basic.yml

image-rs now is a dependency of CDH, thus any change upon image-rs should be test on CDH too.
related to #918

ci: allow CDH ci to be triggered by image-rs changes

---

confidential-data-hub/hub/Cargo.toml

Not an ideal fix but allows trustee to keep both of its guest-components dependencies pointing to the same version.
More details: https://github.com/confidential-containers/guest-components/pull/816#issuecomment-2537669124

cdh: allow Trustee to bump Aliyun KMS plugin

---

.github/workflows/cdh_basic.yml

Due to https://github.com/confidential-containers/guest-components/commit/29711496a38bad2cb9597d8954b306435f95a3e4 musl build will be triggered when the platform is not s390x and powerpc during the `Build and install` step. Thus we do not need this new round to do a duplicated musl build test.

CI: delete musl build for CDH

---

attestation-agent/attestation-agent/src/bin/grpc-aa/main.rs
attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs
attestation-agent/attestation-agent/src/bin/ttrpc-aa.rs
attestation-agent/attestation-agent/src/bin/ttrpc_dep/server.rs
attestation-agent/attestation-agent/src/bin/ttrpc_dep/ttrpc_protocol/attestation_agent.rs
attestation-agent/attestation-agent/src/bin/ttrpc_dep/ttrpc_protocol/attestation_agent_ttrpc.rs
attestation-agent/attestation-agent/src/lib.rs
attestation-agent/kbs_protocol/src/ttrpc_protos/attestation_agent.rs
attestation-agent/kbs_protocol/src/ttrpc_protos/attestation_agent_ttrpc.rs
attestation-agent/protos/attestation-agent.proto

This commit deletes `UpdateConfiguration` API for AA, also adds a new cmdline parameter `--initdata` for AA to check initdata when launching. The two changes are for initdata feature.
The deletion of `UpdateConfiguration` would help avoid a partial initialized AA.

AA: deletes `UpdateConfiguration` API and add `--initdata` launch parameter

---

Cargo.lock
attestation-agent/coco_keyprovider/Cargo.toml
attestation-agent/coco_keyprovider/build.rs

shadow is actually not used in the project. This will resolve the CI error like https://github.com/confidential-containers/guest-components/actions/runs/13758440224/job/38469596953?pr=940

coco_keyprovider: abondon shadow dependency

---

image-rs/src/signature/policy/cosign/mod.rs

the original aliyun registry is personal so the network is not always good thus causing flaky CIs. We consider removing it, because the test case is duplicated with the one of
```
ghcr.io/confidential-containers/test-container-image-rs:cosign-signed
```
and with key
```
test_data/signature/cosign/cosign3.pub
```
Fixes #918

image-rs: delete duplicated unit test case

---

attestation-agent/attester/src/lib.rs

It is very common for people to build the kbs-client without support for the platform that they want to attest. A lot of people either don't notice or understand our existing warning.
To clarify things a little bit, make the warning we print when enabling the sample attester more detailed.

attesters: improve sample warning

---

ocicrypt-rs/src/helpers.rs

Some of our dependabot PRs are blocked by the linter complaining about the format of this content. Let's see if this fixes it.

ocicrypt-rs: fix doc comment format

---

rust-toolchain.toml

rust-toolchain will record the current cargo and rust toolchain version to build the project.
See https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file for more details.
cc @larrydewey

toolchain: add rust toolchain file

---

attestation-agent/attestation-agent/src/config/mod.rs

When we do not explicitly set the fields in AA's config file like
```
[token_configs.coco_as]
url = "http://127.0.0.1:8000"
...
[token_configs.kbs]
url = "https://127.0.0.1:8080"
```
The launch of AA will fail saying that the launch config is not valid. This is not expected in scenarios no attestation token is needed for AA, and users only rely on AA's get_evidence APIs. Some other scenarios are those where the specified Attestation Token will never be accessed.
In such scenarios the url fields do not matters, thus we set default values. Note that the url fields are used lazily when the get_token API is called, so it is safe to set an empty value.

AA: set default URL field for coco_as and kbs token field

---

.github/workflows/links.yml

Before we get closer to a better solution of link checker, let's temporarily disable this link checker.
This is fair and we can do fix-ups to broken links after the link checker goes back well.

ci: disable link checker temporarily

---

Cargo.lock
Cargo.toml
attestation-agent/attester/src/tsm_report/mod.rs
image-rs/tests/credential.rs
image-rs/tests/registry_configuration.rs
image-rs/tests/signature_verification.rs

The new version of tempfile changes API `into_path` to `keep`
Close #997

chore(dep): update tempfile to 3.20

---

Cargo.lock
attestation-agent/attester/Cargo.toml
attestation-agent/attester/src/snp/hostdata.rs
attestation-agent/attester/src/snp/mod.rs

Updated the SNP Attester to use version 6.0.0 of the VIRTEE SEV crate. Minor code adjustments were made to accommodate the library's new report-handling logic, but the overall functionality remains unchanged.
This will also add compatibility to the changes introduced in https://github.com/confidential-containers/trustee/pull/785, so both will need to be part of compatible releases.

Update SNP Attester

---

Cargo.lock
confidential-data-hub/README.md
confidential-data-hub/example.config.json
confidential-data-hub/example.config.toml
confidential-data-hub/hub/src/bin/grpc_server/mod.rs
confidential-data-hub/hub/src/bin/ttrpc_server/mod.rs
confidential-data-hub/hub/src/config.rs
confidential-data-hub/hub/src/error.rs
confidential-data-hub/hub/src/hub.rs
confidential-data-hub/hub/src/image/ocicrypt_config.json
image-rs/Cargo.toml
image-rs/libs/test-utils/src/lib.rs
image-rs/src/auth/auth_config.rs
image-rs/src/auth/mod.rs
image-rs/src/builder.rs
image-rs/src/config.rs
image-rs/src/decoder/mod.rs
image-rs/src/decrypt.rs
image-rs/src/image.rs
image-rs/src/lib.rs
image-rs/src/pull.rs
image-rs/src/registry/mod.rs
image-rs/src/resource/mod.rs
image-rs/src/signature/mod.rs
image-rs/src/signature/policy/cosign/mod.rs
image-rs/src/snapshots/mod.rs
image-rs/src/stream/mod.rs
image-rs/src/stream/unpack.rs
ocicrypt-rs/src/blockcipher/mod.rs
ocicrypt-rs/src/encryption.rs

This PR is mainly for move image-pull to cdh. It improves the log printing after CDH RPC call failure to keep the error information consistent with that when calling image-rs directly, and avoids a lot of useless debug trace information.
In addition, this PR includes an additional commit to abandon the Unknown Snapshot type. Please see the commit message for the specific reason.  cc @ChengyuZhu6

CDH/image-rs | promote error information printing

---

Cargo.lock
attestation-agent/attester/Cargo.toml

Simply bumping the dependency to 6.2.1. There are some minor parsing bugs on 6.0.0 that get handled here and it would be good to include here to avoid complications later. No code changes required.

Bumping SEV library to 6.2.1

---

attestation-agent/kbs_protocol/test/policy.rego

Trustee multi-device support changed the EAR token cpu submod path to include an index.
Update rcar_client test policy rules accordingly to get the test passing. Without the change, the test fails with an 'unauthorized' error.

kbs_protocol: update rcar_client test policy rules

---

confidential-data-hub/example.config.toml
confidential-data-hub/hub/src/config.rs

Now the registry auth is a little different from other secrets. It is not confidential because the host side of CoCo needs the auth to pull manifest.
In peerpod scenario, we need a fixed path of registry auth file inside the guest to be set from the control tunnel. But after moving guest pull from kata-agent to CDH, the auth uri can only be set via CDH.toml via initdata. This would make burden to users. To keep the previous behavior, we use this env to override the value.
cc @stevenhorsman @mkulke

CDH: adds support to read auth URI from the env

---

confidential-data-hub/example.config.json
confidential-data-hub/example.config.toml
image-rs/src/config.rs

Now the registry configuration takes effect via CDH configuration file, but we did not show it in the example config.

CDH: add registy configuration item for example config

---

.github/workflows/image_rs_build.yml
.github/workflows/ocicrypt_rs_build.yml

Make sure apt package db is up-to-date before install. Otherwise we might get 404's for some packages.

ci: fix image-rs and ocicrypt-rs build dependency installation

---

confidential-data-hub/Makefile
confidential-data-hub/docs/SEALED_SECRET.md

The eHSM project is no longer maintained so it's better to make it disabled by default.

cdh: disable eHSM by default

---

Cargo.lock
Cargo.toml

Due to the nature of this project, this isn’t especially easy for me to test locally, but I tried a [test build](https://koji.fedoraproject.org/koji/taskinfo?taskID=136199932) of the [`trustee-guest-components` package](https://src.fedoraproject.org/rpms/trustee-guest-components) in Fedora with `rstest` 0.26, and that went well.
(My motivation is that I am working on removing the last dependencies on compat packages for older versions of `rstest` in Fedora, and it’s our policy to offer patches upstream wherever possible.)

Update rstest from 0.17 to 0.26

---

.github/workflows/publish-artifacts.yml

We use rust-toolchain.toml to pin toolchain version and actions-rust-lang/setup-rust-toolchain knows to set an override accordingly.
However, the repository must be checked out for rust-toolchain.toml to be available. Without it, the latest Rust stable is used.
Building CDH using rust stable fails currently so the publish to ORAS post-merge job fails to run.
Fixes: #1116

workflows: publish artifacts: checkout code before toolchain install
