confidential-containers/guest-components

CODEOWNERS
Apply to be one of the code owners of this repository.
=> Modify CODEOWNERS to add a new owner.

tests/README.md
Update the docs for integration test, which is useful for readers using the test
=> docs: update docs for integration test

src/image.rs
Earlier ImageClient::pull_image used to return early if the image had already been pulled. In this case, the second bundle created using an existing image would not get populated.
In this PR, if the image as already been pulled, then prior to returning early, the bundle is setup.
Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>
=> Allow multiple bundles to be created from the same image

signature/src/policy/ref_match.rs, src/decoder/mod.rs, src/pull.rs, src/snapshots/mod.rs, src/snapshots/overlay.rs
needed to get CI working again
=> fix clippy warnings with nightly toolchain

Cargo.toml, signature/Cargo.toml, src/pull.rs
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
=> dependencies: update ocicrypt-rs

docs/image_auth.md
Backgrounds, Goals, Work process and considerations of image auth.
This is linked to https://github.com/confidential-containers/image-rs/issues/63.
cc @stevenhorsman @liudalibj
=> docs: image auth design

Cargo.toml
=> cargo: Bump ocicrypt-rs to v0.2.0

src/image.rs
When an image to be pulled has duplicated layers, the 2nd layer will write the same layer data and raise layer. This is because the time to update the database that stores layer metadata is after pulling all layers of an image. This commit
will try to construct a new layer list to be pulled via deduplicating the layers of the OciManifest.
Close https://github.com/confidential-containers/image-rs/issues/76
Signed-off-by: Xynnn007 <xynnn@linux.alibaba.com>
=> fix: pulling error when image has duplicated layers

scripts/build_attestation_agent.sh, tests/README.md, tests/common/mod.rs, tests/credential.rs, tests/image_decryption.rs, tests/signature_verification.rs
- removed sample kbc from the integration test module
Close https://github.com/confidential-containers/image-rs/issues/85
=> Integration test: remove sample kbc

src/bundle.rs, src/config.rs, src/decrypt.rs, src/signature/mechanism/simple/mod.rs, src/signature/mechanism/simple/sigstore.rs
Add some additional unit tests.
Fixes: #93.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> Add more unit tests

.github/workflows/ci.yml, .github/workflows/ci_eaa_kbc.yml, Cargo.toml, build.rs, src/config.rs, src/decoder/mod.rs, src/decrypt.rs, src/image.rs, src/pull.rs, src/secure_channel.rs, tests/credential.rs, tests/image_decryption.rs, tests/signature_verification.rs
The image-rs has too heavy dependency, about 500 crates get compiled. So let's start to reduce dependencies.
=> Prepare to reduce dependency

CODEOWNERS
@Xynnn007 make lots of contributions on signature module, container registry auth support, integration tests, documents: https://github.com/confidential-containers/image-rs/commits?author=Xynnn007
=> codeowners: Add Xynnn007 as maintainer

.github/workflows/ci_eaa_kbc.yml
=> ci: Update filter paths for signature module

.github/workflows/ci.yml, .github/workflows/ci_eaa_kbc.yml, Cargo.toml, src/config.rs, src/decoder/mod.rs, src/image.rs, src/secure_channel.rs, src/signature/mechanism/cosign/mod.rs, src/signature/mechanism/mod.rs, src/signature/mechanism/simple/mod.rs, src/signature/mod.rs, src/signature/payload/simple_signing.rs, src/signature/policy/policy_requirement.rs, src/snapshots/mod.rs, src/snapshots/occlum/mod.rs, src/snapshots/overlay.rs, tests/credential.rs, tests/signature_verification.rs
Second part to simplify dependency chain of image-rs.
=> Second part to simplify dependency chain

src/unpack.rs
When a layer is duplicated but not recorded in layer_db, it should be treated as "broken" and be deleted. Then the newly pulled layer data can be written, instead of raising an error and exit.
cc @arronwy
=> fix: delete broken layer when duplication detected

src/image.rs, src/pull.rs
Improve pull performance for image with multiple layers and small CPU num without needless schedule overhead.
Fixes: #145
=> pull: Add max concurrent download limit support

image-rs/Cargo.toml, image-rs/src/config.rs, image-rs/src/image.rs, image-rs/src/lib.rs, image-rs/src/nydus/mod.rs, image-rs/src/nydus/service.rs, image-rs/src/nydus/utils.rs, image-rs/src/pull.rs
Integrate nydus related services into image-rs initially. Only nydus FUSE service is supported right now.
=> feat: use ndyus to speed up the image deployment process in image-rs

.github/workflows/links.yml
=> ci: add link checker workflow

attestation-agent/README.md, attestation-agent/deps/crypto/src/symmetric.rs, attestation-agent/deps/resource_uri/src/lib.rs, attestation-agent/docker/Dockerfile.keyprovider, attestation-agent/docs/IMAGE_ENCRYPTION.md, attestation-agent/kbc/src/cc_kbc/README.md, attestation-agent/kbc/src/eaa_kbc/README.md, attestation-agent/kbc/src/offline_fs_kbc/README.md, image-rs/Cargo.toml, image-rs/docs/ccv1_image_security_design.md, image-rs/docs/design.md, image-rs/docs/image_auth.md, image-rs/docs/pull_image_with_nydus.md, image-rs/docs/quickstart/image_signing.md, image-rs/src/resource/kbs/grpc.rs, image-rs/src/resource/kbs/mod.rs, image-rs/src/signature/README.md, image-rs/src/signature/mechanism/simple/README.md, image-rs/tests/README.md, image-rs/tests/signature_verification.rs
Not sure how to fix the last remaining error:
> Errors in ./image-rs/test_data/generate_test_data.md
> - [404] https://github.com/confidential-containers/attestation-agent/blob/main/sample_kbs/README.md | Failed: Network error: Not Found
=> docs: update links to new repo and fix broken links

image-rs/src/image.rs, image-rs/src/verity.rs
Refine implementation of dm-verity.
=> image-rs: refine implementation of dm-verity

image-rs/src/verity.rs
Add `sha1`hash algorithm support in dm-verity.
=> image-rs: add sha1 hash algorithm support in dm-verity

image-rs/src/verity.rs
To support to convert `tarfs dm-verity option` from remote snapshotter to `dmVerityOption`, such as
`tarfs dm-verity option`: `"1024,524288,sha256:9de18652fe74edfb9b805aaed72ae2aa48f94333f1ba5c452ac33b1c39325174"`
=> verity: support parsing options from remote snapshotter

image-rs/src/image.rs
To support image pulling in the guest without forked containerd, the image name will be passed from remote snapshotter, the format is such as `imageurl=cmVnaXN0cnkuY24taGFuZ3pob3UuYWxpeXVuY3MuY29tL2dvb2dsZV9jb250YWluZXJzL3BhdXNlOjMuNg==`, which the image name is encoded by `base64`.  According to the encoded image name example, its decoded image name is `registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6`
=> image: Add a function to get image name from remote

image-rs/Cargo.toml, image-rs/src/image.rs, image-rs/src/lib.rs, image-rs/src/verity/dmverity.rs, image-rs/src/verity/mod.rs
add feature gate for verity. 
Fixes #314
=> image-rs: add feature gate for verity

.github/workflows/api-server-rest-basic.yml, api-server-rest/Makefile
Add makefile to api-server and workflow to test it
=> Api server rest makefile

attestation-agent/lib/src/token.rs
The current peerpod code path that parses the agent config file does not strip the prefix, hence the kbs_host addr (it's not just a "kbs_host" it's "protocol + host + port") ends up being: `cc_kbc::http://1.2.3.4:8080`.
After this change a pod i'm able to get a token and a secret resource from kbs on a peerpod deployment:
```bash
k exec -it deploy/nginx-caa -- curl http://127.0.0.1:8006/cdh/resource/default/key/1
ohai
```
on kbs:
=> attestation-agent: fix extraction of peerpod kbs host addr extraction in token code

confidential-data-hub/kms/Cargo.toml
=> cdh/kms: add rustls-tls feature for aliyun

attestation-agent/attester/Cargo.toml
Update csv-rs to be compatible with openssl-sys 0.9.94.
Signed-off-by: fangbaoshun <fangbaoshun@hygon.cn>
=> aa/attester: Update csv-rs dep to rev 9d8882e.

attestation-agent/attester/src/tdx/mod.rs
The TDX attester code already tries very hard to ensure the report_data passed has the correct size. Because of that, initializing tdx_attest_rs::tdx_report_data_t should never fail. However, .try_into() returns a Result we must process.
Currently, the code just raises an error without a good reason what happened. Alternatively, we could just unwrap() but that could panic. The third approach is to just initialize tdx report data to zero and catch the attestation result later.
This picks the third option and changes the code to use a const to make sure Vec size conflicts are less likely to happen.
This was initially discussed in https://github.com/confidential-containers/guest-components/pull/434#discussion_r1456983754 and I wanted to have the conversation separately so that I could just …
=> RFC: attester: tdx: try not to error on broken report_data

.github/workflows/image_rs_build.yml
trigger nydus test in workflow.
=> workflow: trigger nydus test in workflow

attestation-agent/attester/README.md
=> AA/attester: add README docs

confidential-data-hub/hub/src/bin/confidential-data-hub/main.rs
fixes #489 
In the CoCo scenario the CDH configuration is dynamic, since it is specific to the container workload, so using /etc, which might reside on a read-only volume is not a good default in those cases. We need a way to override this (to reference a config in /run). --config is not an option, since the process is spawned statically w/o cli arguments by kata-agent.
Hence the configuration path lookup has been adjusted in this way:
- --config is optional
- if --config is unset, consider env.CDH_CONFIG_PATH
- defaults to DEFAULT_CONFIG_PATH if both are unset
=> cdh: make the config path configurable by env

Cargo.lock, Cargo.toml, image-rs/Cargo.toml
=> dep: update ring to 0.17

attestation-agent/attester/src/tdx/mod.rs
Some systems do not yet provide the ability to extend runtime measurement so add a check to allow a more meaningful error to be returned.
=> attester: tdx: Improve extend runtime measurement handling

confidential-data-hub/docs/SEALED_SECRET.md, confidential-data-hub/docs/kms-providers/ehsm-kms.md, confidential-data-hub/kms/src/plugins/ehsm/README.md
1. update `README.md` of eHSM-KMS, which provides guidance for setting up eHSM-KMS.
2. add `ehsm-kms.md` for kms providers documentation, which provides guidance for using eHSM-KMS.
=> cdh/docs: add/update eHSM document

attestation-agent/kbs_protocol/src/client/rcar_client.rs
I've noticed a few people running into an error like `AA-KBC get token failed: RCAR handshake failed: Get token failed because of RCAR handshake retried 5 times.` which is not very useful. This error can be caused by the KBS URI being incorrect or by the IKBS rejecting the evidence or a number of other situations.
Fixes https://github.com/confidential-containers/guest-components/issues/564
=> aa: surface error from RCAR handshake

.github/workflows/aa_basic.yml, .github/workflows/aa_cc_kbc.yml, .github/workflows/aa_crypto.yml, .github/workflows/aa_eaa_kbc.yml, .github/workflows/aa_occlum_sgx.yml, .github/workflows/aa_sample_keyprovider.yml, .github/workflows/aa_sev_kbc.yml, .github/workflows/api-server-rest-basic.yml, .github/workflows/cdh_basic.yml, .github/workflows/image_rs_build.yml, .github/workflows/ocicrypt_rs_build.yml
Make CI only build when there is a PR, or a direct push to main.
=> ci: Remove duplicate build when a PR is merged to main

attestation-agent/attestation-agent/src/lib.rs
Before this commit, if we disabled eventlog recording in AA's config, there will still be a file `/run/attestation-agent/eventlog` but with no contents.
This file would be collected by tdx attester, treated as a valid AAEL. But on CoCo-AS side the AAEL parser will fail because nothing is in it.
This commit will avoid creating this file once we disabled in AA's config.
cc @ChengyuZhu6
=> AA: avoid creating AAEL if it is disabled

attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs, attestation-agent/attestation-agent/src/bin/ttrpc-aa/server.rs, attestation-agent/attestation-agent/src/lib.rs
The attestation-agent provided two binaries `aa-ttrpc` and `aa-grpc`. However, due to the existing of Mutex, we can't handle multiple `get_token()` and `get_evidence()` requests at the same time.
This commit removes Mutex from `attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs` and `attestation-agent/attestation-agent/src/bin/ttrpc-aa/server.rs` to solve this problem.
=> AA: fix timeout when processing multiple incoming requests

Cargo.lock, image-rs/src/signature/mechanism/simple/verify.rs
=> manual dependency updates

confidential-data-hub/golang/README.md
=> cdh:golang: fix typo in README

.github/workflows/publish-artifacts.yml
publish CI has been failing due to this
=> ci: add missing apt-get update on publish wf

attestation-agent/attester/Cargo.toml
Synchronize with version used in other CoCo components
=> Bump from 3.1.1 to 4.0.0

Cargo.lock, api-server-rest/openapi/api.json
=> chore: update utoipa to v5.3.0

.github/workflows/image_rs_build.yml, .github/workflows/ocicrypt_rs_build.yml, .github/workflows/publish-artifacts.yml, Cargo.lock
please see concrete commit messages for each commit.
Close #851
=> Chore update josekit version & update rust toolchain version to v1.83.0

Cargo.lock, attestation-agent/coco_keyprovider/Cargo.toml, attestation-agent/coco_keyprovider/build.rs
=> chore(deps): update shadow_rs to v0.37.0

Cargo.lock, image-rs/Cargo.toml, image-rs/src/signature/policy/simple/verify.rs
=> chore: update sequoia-openpgp to 2.0.0

attestation-agent/attestation-agent/src/config/coco_as.rs, attestation-agent/attestation-agent/src/config/kbs.rs, attestation-agent/attestation-agent/src/config/mod.rs, attestation-agent/attestation-agent/src/lib.rs, attestation-agent/attestation-agent/test/config1.toml, attestation-agent/attestation-agent/test/config2.toml, attestation-agent/attestation-agent/test/config3.toml, attestation-agent/attestation-agent/test/config4.toml, attestation-agent/attestation-agent/test/config6.toml, confidential-data-hub/hub/src/config.rs, confidential-data-hub/kms/src/error.rs, image-rs/src/builder.rs, image-rs/src/config.rs
This patch has some different patches to support moving image pull to CDH work. Please see the concrete commit messages.
cc @mkulke
=> AA/CDH: some fix-up work to support moving image-pull to CDH

Cargo.lock, Cargo.toml, attestation-agent/attestation-agent/Cargo.toml, attestation-agent/attester/Cargo.toml, attestation-agent/attester/src/csv/mod.rs, attestation-agent/attester/src/hygon_dcu/mod.rs, attestation-agent/attester/src/lib.rs, attestation-agent/kbs_protocol/Cargo.toml
This patch brings in Hygon DCU device attestation support, together with some fixes for csv attester.
=> Add Hygon DCU device attestation support

Cargo.lock, Cargo.toml, attestation-agent/attestation-agent/src/bin/grpc-aa/main.rs, attestation-agent/attestation-agent/src/bin/grpc-aa/server.rs, attestation-agent/attestation-agent/src/bin/ttrpc-aa.rs, attestation-agent/attestation-agent/src/bin/ttrpc_dep/server.rs, attestation-agent/attestation-agent/src/bin/ttrpc_dep/ttrpc_protocol/attestation_agent.rs, attestation-agent/attestation-agent/src/bin/ttrpc_dep/ttrpc_protocol/attestation_agent_ttrpc.rs, attestation-agent/attestation-agent/src/eventlog/mod.rs, attestation-agent/attestation-agent/src/initdata.rs, attestation-agent/attestation-agent/src/lib.rs, attestation-agent/attestation-agent/src/token/coco_as.rs, attestation-agent/attestation-agent/src/token/kbs.rs, attestation-agent/attestation-agent/src/token/mod.rs, attestation-agent/attester/src/lib.rs, attestation-agent/attester/src/se/mod.rs, attestation-agent/kbs_protocol/Cargo.toml, attestation-agent/kbs_protocol/src/builder.rs, attestation-agent/kbs_protocol/src/client/mod.rs, attestation-agent/kbs_protocol/src/client/rcar_client.rs, attestation-agent/kbs_protocol/src/evidence_provider/aa_ttrpc.rs, attestation-agent/kbs_protocol/src/evidence_provider/mock.rs, attestation-agent/kbs_protocol/src/evidence_provider/mod.rs, attestation-agent/kbs_protocol/src/evidence_provider/native.rs, attestation-agent/kbs_protocol/src/ttrpc_protos/attestation_agent.rs, attestation-agent/kbs_protocol/src/ttrpc_protos/attestation_agent_ttrpc.rs, attestation-agent/protos/attestation-agent.proto
This patch adds initdata toml support to KbsProtocol.
Close #1002
=> AA | Add initdata plaintext support
